### ISSUE TITLE
How to replace gstreamer from the examples gstreamer-receive and gstreamer-send

### ISSUE THREAD

**Issue by joeky888** [pions/webrtc#102]
How could I replace gstreamer with something more lightweight c lib 

or pure go lib if I only want to work with audio (non-GUI app)?

Any ideas?

Thanks in advance :)

**Comment by joeky888** [comment]
> you can describe what you want to do in more detail.

I would like to make a simple and lightweight cli audio chat app using pions webrtc.

Gstreamer seems to be a heavyweight dependency for me.

**Comment by deepch** [comment]
I think you can do this. But still there will be two dependencies this libssl developers want to remove it and I think this is very correct.
and you receive audio device pcm audio you can mux it to g711 alaw / ulaw 
but webrtc does not support as I understand it pcm, alaw, ulaw, aac need encode to opus

1) you need find go project use opus https://github.com/hraban/opus
2) you need receive raw pcm audio you microphone 
3) pcm -> encode to opus
4) next look sample and use (opus, err := peerConnection.NewRTCTrack)  opus.Samples <-  send packet opus
5) you need write communicate over http or tcp or any other proto for key exchange
6) write receive look sample it read Chanel and decode packet use https://github.com/hraban/opus to pcm
7) send pcm packet to sound output device 

if you write, it no need gui and depending libssl, and libopus

**Comment by deepch** [comment]
libssl <- I would really like that the developers deleted this dependence
and then one would say proudly that this is on pure golang ;)

**Comment by deepch** [comment]
I can do this a little later, since I was on vacation.

**Comment by gedw99** [comment]
What about https://github.com/nareix/joy4

Looks like a full bodied replacement of gstreamer to me.
What do you think ?

**Comment by joeky888** [comment]
> What about https://github.com/nareix/joy4

I don't think it has an opus decoder/encoder in it.

**Comment by gedw99** [comment]
No it doesn't.
But I am thinking it's smarter to add it to that lib because it's setup for
muxing and transcoding that's all.

**Comment by joeky888** [comment]
Cross-platform is better, 
but for now I am working on linux so I am using alsa lib to play the audio for testing.

And the following code does not work, it only produces noises.

```diff
diff --git a/examples/gstreamer-receive/main.go b/examples/gstreamer-receive/main.go
index 05174db..2466112 100644
@@ -8,9 +8,10 @@ import (
 	"bufio"
 	"encoding/base64"
 
+	"github.com/cocoonlife/goalsa"
 	"github.com/pions/webrtc"
-	"github.com/pions/webrtc/examples/gstreamer-receive/gst"
 	"github.com/pions/webrtc/pkg/ice"
+	"gopkg.in/hraban/opus.v2"
 )
 
 func main() {
@@ -46,14 +47,54 @@ func main() {
 
 	// Set a handler for when a new remote track starts, this handler creates a gstreamer pipeline
 	// for the given codec
+
+	const sampleRate = 48000
+	const channels = 2
+
+	dec, err := opus.NewDecoder(sampleRate, channels)
+	if err != nil {
+		fmt.Println("Decoder error")
+		panic(err)
+	}
+
+	out, err := alsa.NewPlaybackDevice("default", 1, alsa.FormatS16LE, sampleRate, alsa.BufferParams{})
+	if err != nil {
+		panic(err)
+	}
+
+	// require ALSA device
+	if out == nil {
+		fmt.Println("Device is nil!!")
+	} else {
+		fmt.Println(out)
+	}
+	// close device when finished
+	defer out.Close()
+
 	peerConnection.Ontrack = func(track *webrtc.RTCTrack) {
 		codec := track.Codec
 		fmt.Printf("Track has started, of type %d: %s \n", track.PayloadType, codec.Name)
-		pipeline := gst.CreatePipeline(codec.Name)
-		pipeline.Start()
+
+		pcm := make([]int16, 100000)
 		for {
 			p := <-track.Packets
-			pipeline.Push(p.Raw)
+
+			_, err := dec.Decode(p.Raw, pcm)
+
+			if err != nil {
+				fmt.Println("Decode error")
+				panic(err)
+			}
+
+			if pcm != nil {
+				// play!
+				out.Write(pcm)
+
+				fmt.Println("before:")
+				fmt.Println(p.Raw)
+				fmt.Println("after:")
+				fmt.Println(pcm)
+			}
 		}
 	}
```

**Comment by Sean-Der** [comment]
Lots of info here, will try my best to respond to everything!

# Is GStreamer required.
Nope! We have some examples that use GStreamer, but we also have others that save VP8 straight to disk with no extra dependencies [save-to-disk](https://github.com/pions/webrtc/tree/master/examples/save-to-disk) 

# Dropping libssl
me and @trivigy talk about this a lot. It is going to be quite the undertaking, but we are going to get it done! I have a list of small issues I want closed, after that we can cut a new release and start another big feature push.

# Adding more examples like libopus, ALSA, joy4
I would love this! The bar for getting code into `/examples` is really low for me. As long as they build, no lint errors I have no problem. You can add any new dependencies you want etc... just to show off what you can do with `pion-WebRTC`

# Sample code
You should pass `p.Payload` that is just the body of the RTP packets. `p.Raw` includes the RTP headers etc...

**Comment by joeky888** [comment]
> You should pass p.Payload that is just the body of the RTP packets. p.Raw includes the RTP headers etc...

Thanks! I finally heard some voices, but the voice is so deep, like I am using a voice changer or something..

**Comment by Sean-Der** [comment]
Nice! If you can hear voices I don't think there is anything left to tune with `pion-WebRTC`, since it just transports the audio buffers. If it was a bug at that level it would completely corrupt it (not change the pitch)

I would try playing with things like rate+format+channels and see if any of that helps.

**Comment by joeky888** [comment]
> I would try playing with things like rate+format+channels and see if any of that helps.

Change `const channels = 2` to `const channels = 1` the deep voice was fixed.

Thanks again! You guys are amazing!

**Comment by deepch** [comment]
I look at you it turned out to be done. It is perfectly.

**Comment by Sean-Der** [comment]
Awesome glad to hear it worked @joeky888 :) Is there anything else I can do to help out, or mind if I close the issue?

If you are interested I would love to have your `/examples` in the repo, could really help another developer in the future!

**Comment by joeky888** [comment]
> mind if I close the issue?

Wait, I didn't add the recording code there. I'll make it as soon as possible.

 > I would love to have your /examples in the repo.

Sure, just do it. But it only works on Linux. I would like to rewrite it using ether [oto](https://github.com/hajimehoshi/oto) or openal.

**Comment by joeky888** [comment]
Edit:

I will close it anyway. I will update my code and post it here, thanks!

**Comment by joeky888** [comment]
Hello guys, me again.

I am trying to finish the recording part in `examples/gstreamer-send`.

Once again the browser only produces noises.

Here is how I did it:

```diff
diff --git a/examples/gstreamer-send/jsfiddle/demo.js b/examples/gstreamer-send/jsfiddle/demo.js
index 08de6db..fcbba10 100644
@@ -27,7 +27,7 @@ pc.onicecandidate = event => {
   }
 }
 
-pc.createOffer({offerToReceiveVideo: true, offerToReceiveAudio: true}).then(d => pc.setLocalDescription(d)).catch(log)
+pc.createOffer({offerToReceiveVideo: false, offerToReceiveAudio: true}).then(d => pc.setLocalDescription(d)).catch(log)
 
 window.startSession = () => {
   let sd = document.getElementById('remoteSessionDescription').value
diff --git a/examples/gstreamer-send/main.go b/examples/gstreamer-send/main.go
index 008679f..47a1c6a 100644
@@ -8,9 +8,13 @@ import (
 	"bufio"
 	"encoding/base64"
 
+	"github.com/cocoonlife/goalsa"
 	"github.com/pions/webrtc"
-	"github.com/pions/webrtc/examples/gstreamer-send/gst"
+
+	// "github.com/pions/webrtc/examples/gstreamer-send/gst"
 	"github.com/pions/webrtc/pkg/ice"
+	"github.com/pions/webrtc/pkg/media"
+	"gopkg.in/hraban/opus.v2"
 )
 
 func main() {
@@ -89,7 +93,56 @@ func main() {
 	fmt.Println(base64.StdEncoding.EncodeToString([]byte(answer.Sdp)))
 
 	// Start pushing buffers on these tracks
-	gst.CreatePipeline(webrtc.Opus, opusTrack.Samples).Start()
-	gst.CreatePipeline(webrtc.VP8, vp8Track.Samples).Start()
+	const channels = 2
+	const sampleRate = 48000
+	const format = alsa.FormatS16LE
+	const pcmsize = 480
+
+	recorder, err := alsa.NewCaptureDevice("default", channels, format, sampleRate,
+		alsa.BufferParams{BufferFrames: 0, PeriodFrames: pcmsize, Periods: pcmsize})
+
+	if err != nil {
+		panic(err)
+	}
+	defer recorder.Close()
+
+	enc, err := opus.NewEncoder(sampleRate, channels, opus.AppVoIP)
+	if err != nil {
+		panic(err)
+	}
+
+	pcm := make(chan []int16)
+
+	/* Recording audio */
+	go func() {
+		p := make([]int16, pcmsize)
+
+		for {
+			recorder.Read(p)
+			pcm <- p
+		}
+	}()
+
+	/* Send audio */
+	go func() {
+		p := make([]int16, pcmsize)
+		opusdata := make([]byte, 10000)
+
+		for {
+			p = <-pcm
+
+			n, err := enc.Encode(p, opusdata) // pcm to opus
+			if err != nil {
+				panic(err)
+			}
+			opusdata = opusdata[:n] // Remove unused space after encoding to opus
+
+			opusTrack.Samples <- media.RTCSample{Data: opusdata, Samples: uint32(pcmsize)}
+		}
+	}()
+
+	// gst.CreatePipeline(webrtc.Opus, opusTrack.Samples).Start()
+	// gst.CreatePipeline(webrtc.VP8, vp8Track.Samples).Start()
+
 	select {}
 }
```

I would be appreciated with your help! :)

**Comment by joeky888** [comment]
I created a repo to replace gstreamer

Links: https://github.com/joeky888/pions-examples

Feel free to use it!

**Comment by joeky888** [comment]
I added a packetizer to add rtp headers (I think)

still no luck :(

```diff
diff --git a/examples/gstreamer-send/main.go b/examples/gstreamer-send/main.go
index 008679f..5f65d67 100644
@@ -1,6 +1,8 @@
 package main
 
 import (
+	"crypto/rand"
+	"encoding/binary"
 	"fmt"
 	"io"
 	"os"
@@ -8,9 +10,14 @@ import (
 	"bufio"
 	"encoding/base64"
 
+	"github.com/cocoonlife/goalsa"
 	"github.com/pions/webrtc"
-	"github.com/pions/webrtc/examples/gstreamer-send/gst"
+
+	// "github.com/pions/webrtc/examples/gstreamer-send/gst"
 	"github.com/pions/webrtc/pkg/ice"
+	"github.com/pions/webrtc/pkg/media"
+	"github.com/pions/webrtc/pkg/rtp"
+	"gopkg.in/hraban/opus.v2"
 )
 
 func main() {
@@ -26,11 +33,19 @@ func main() {
 		panic(err)
 	}
 
+	const channels = 2
+	const sampleRate = 48000
+	const format = alsa.FormatS16LE
+	const pcmsize = 480
+	const mtu = 1400
+	PayloadTypeOpus := uint8(webrtc.DefaultPayloadTypeOpus)
+	opuscodec := webrtc.NewRTCRtpOpusCodec(PayloadTypeOpus, sampleRate, channels)
+
 	/* Everything below is the pion-WebRTC API, thanks for using it! */
 
 	// Setup the codecs you want to use.
 	// We'll use the default ones but you can also define your own
-	webrtc.RegisterDefaultCodecs()
+	webrtc.RegisterCodec(opuscodec)
 
 	// Create a new RTCPeerConnection
 	peerConnection, err := webrtc.New(webrtc.RTCConfiguration{
@@ -61,14 +76,14 @@ func main() {
 	}
 
 	// Create a video track
-	vp8Track, err := peerConnection.NewRTCTrack(webrtc.DefaultPayloadTypeVP8, "video", "pion2")
-	if err != nil {
-		panic(err)
-	}
-	_, err = peerConnection.AddTrack(vp8Track)
-	if err != nil {
-		panic(err)
-	}
+	// vp8Track, err := peerConnection.NewRTCTrack(webrtc.DefaultPayloadTypeVP8, "video", "pion2")
+	// if err != nil {
+	// 	panic(err)
+	// }
+	// _, err = peerConnection.AddTrack(vp8Track)
+	// if err != nil {
+	// 	panic(err)
+	// }
 
 	// Set the remote SessionDescription
 	offer := webrtc.RTCSessionDescription{
@@ -89,7 +104,74 @@ func main() {
 	fmt.Println(base64.StdEncoding.EncodeToString([]byte(answer.Sdp)))
 
 	// Start pushing buffers on these tracks
-	gst.CreatePipeline(webrtc.Opus, opusTrack.Samples).Start()
-	gst.CreatePipeline(webrtc.VP8, vp8Track.Samples).Start()
+
+	recorder, err := alsa.NewCaptureDevice("default", channels, format, sampleRate,
+		alsa.BufferParams{BufferFrames: 0, PeriodFrames: pcmsize, Periods: pcmsize})
+
+	if err != nil {
+		panic(err)
+	}
+	defer recorder.Close()
+
+	enc, err := opus.NewEncoder(sampleRate, channels, opus.AppVoIP)
+	if err != nil {
+		panic(err)
+	}
+
+	pcm := make(chan []int16)
+
+	/* Recording audio */
+	go func() {
+		p := make([]int16, pcmsize)
+		for {
+			recorder.Read(p)
+			pcm <- p
+		}
+	}()
+
+	/* Send audio */
+	go func() {
+		p := make([]int16, pcmsize)
+		opusdata := make([]byte, 1000)
+
+		ran := make([]byte, 4)
+		_, err = rand.Read(ran)
+		if err != nil {
+			panic(err)
+		}
+
+		ssrc := binary.LittleEndian.Uint32(ran)
+
+		packetizer := rtp.NewPacketizer(
+			mtu,
+			opuscodec.PayloadType,
+			ssrc,
+			opuscodec.Payloader,
+			rtp.NewRandomSequencer(),
+			sampleRate,
+		)
+
+		for {
+			p = <-pcm
+
+			n, err := enc.Encode(p, opusdata) // pcm to opus
+			if err != nil {
+				panic(err)
+			}
+			opusdata = opusdata[:n] // Remove unused space after encoding to opus
+
+			packets := packetizer.Packetize(opusdata, pcmsize)
+
+			raw, err := packets[0].Marshal()
+			if err != nil {
+				panic(err)
+			}
+
+			opusTrack.Samples <- media.RTCSample{Data: raw, Samples: uint32(pcmsize)}
+		}
+	}()
+
+	// gst.CreatePipeline(webrtc.Opus, opusTrack.Samples).Start()
+	// gst.CreatePipeline(webrtc.VP8, vp8Track.Samples).Start()
 	select {}
 }
```

**Comment by Sean-Der** [comment]
Hey @joeky888 really nice work with those examples!

You mind posting what isn't working as a finished code sample (gist or in that linked repo) I should have time this weekend to check it out!

Would you be ok with me importing your examples? I will mark you as a coauthor on the commit, but would love if other people could try them out easy!

thanks

**Comment by joeky888** [comment]
> You mind posting what isn't working as a finished code sample

Here it is: https://github.com/joeky888/pions-examples/tree/master/alsa-send

> Would you be ok with me importing your examples?

I don't mind, just do it!
