### ISSUE TITLE
Remove `reftypereturn` instead follow NullString pattern

### ISSUE THREAD

**Issue by Sean-Der** [pions/webrtc#105]
Using a pointer to represent primary data types is prone to error/not self documenting.

Instead replace reftypereturn with `util.NullString util.NullUint16` etc.. they can't be in the WebRTC package since SDP needs to use them as well.

**Comment by trivigy** [comment]
Really going back and forth on this one. I feel like it might be a little too much of a change for now. Can we wait a little with this until the library is a bit more stable so we could identify exactly where this could be placed such that it is not putting too much public api restricting?!

As I said, I am happy to get this story out of the way. Just feel like it may be just a little too early.

**Comment by Sean-Der** [comment]
I opened a PR @trivigy nothing depends on this API currently, so no public facing issues.

It is a fair conversation if it makes sense to use it. Personally as a user I would be confused if something is `int*` instead of `NullInt`, the second is self documenting.

@maxhawkins @kc5nra you guys have thoughts! I am probably overlooking things, I am just trying to steal the existing NullString Go pattern.

**Comment by maxhawkins** [comment]
If you name the package `null` the struct names can be shorter.

`nullvalue.NullBool` -> `null.Bool`

**Comment by Sean-Der** [comment]
I like that @maxhawkins! Will make that change.

You also ok with what/how I am trying to solve the issue? It isn't very Go-like, but I think keeping the WebRTC API is important (so we don't have to document things about WebRTC that already exist)

**Comment by maxhawkins** [comment]
Do you have an example of what it will look like for an end-user to use the API?

The NullBool thing seems right but it's hard to know without seeing it in practice

**Comment by backkem** [comment]
Using the current package it would be:
``` go
ordered := false
pc.CreateDataChannel("data", &webrtc.RTCDataChannelInit{
	Ordered: null.Bool{true, ordered},
})
```
It's probably best if we add constructors where you don't have to manually set the 'Valid' field. Maybe add NewType(v Type) methods? E.g.:
``` go
ordered := false
pc.CreateDataChannel("data", &webrtc.RTCDataChannelInit{
	Ordered: null.NewBool(ordered),
})
```
`null.Bool(ordered)` would be nice but then we'll have to name the structs differently.

**Comment by trivigy** [comment]
@backkem @Sean-Der what happens if we reassign the value? Should there also be functions that are actually updating the underlying `Valid`? Since this is public interface as well, what happens if a user that has multithreading/goroutines starts to update these values? Should there be an internal lock? There are some of the concerns I had a little while back.

**Comment by backkem** [comment]
My thoughts: These structs are not supposed to be passed by reference. You would pass null.Type instead of *null.Type. The value will be copied and you can't change it anymore. If you don't explicitly set a field with a null.Type it will be initialized with Value = false which means the value is 'null'.

**Comment by Sean-Der** [comment]
@trivigy 

* multi-threading
We have the same issue with any value, if a user has an int shared across two threads they need to lock also.

* Valid member
User needs to get/set that as well. It works this way now with SQL, I am not aware of any complaints around `Valid` on that.

**Comment by Sean-Der** [comment]
What is the alternative though? I am totally happy to do something else, but `int*` has the multi-threading issue and is going to cause segfaults when people just assume it is valid.
