### ISSUE TITLE
Support sending H264

### ISSUE THREAD

**Issue by deepch** [pions/webrtc#11]
I do not understand the idea of ​​the project a little

I have rtp or raw stream from rtsp ip camera
I can send my rtp or raw h264 or rtsp stream to browser over webrtc? 

I can write examples that will get the rtp video stream but do not know how to give it to the browser. Does your project plan such a decision?

**Comment by Sean-Der** [comment]
Hi @deepch 

Exactly! We are still working on it, but you will be able to send your H264 to your web browser when we are done (maybe 1 more week) Right now you can receive video and save to disk, try it out [here](https://github.com/pions/webrtc/blob/master/examples/save-to-disk/README.md) to get a feel for it. 

I will take care of making an example that sends video to a browser, when it is done I will close this ticket with the commit. Thanks for checking it out, and excited to get people using it :)

**Comment by deepch** [comment]
Excellent! I will wait with impatience.

**Comment by Sean-Der** [comment]
@deepch Good news! I got sending VP8 [working](https://i.imgur.com/2inQaSH.png) on a branch (videotestsrc coming from GStreamer).

Hopefully not much longer and it will land on master. Thanks for the patience.

**Comment by deepch** [comment]
good news!

VP8 - not supported rtsp camera can h264? or late?

**Comment by deepch** [comment]
I really look forward to it.

**Comment by deepch** [comment]
When will the support for h 264 be?

**Comment by Sean-Der** [comment]
@kc5nra Is working on the last bit needed for sending.

How much more do you think it would take to add H264. If we can just use what you already did once before in C++ ? I don't even care about multiple stream-formats, just an MVP sorta deal.

**Comment by kc5nra** [comment]
@Sean-Der @deepch 
Yep! I will add single and FU-A support for H264 shortly!  Just finishing up the VP8 packetizing

**Comment by colek42** [comment]
@kc5nra if you tag me when this is done I would love to give you a code review.

**Comment by deepch** [comment]
ok im wait and ready test

**Comment by Sean-Der** [comment]
If you are interested the examples have landed for sending video/audio (but only VP8 for video) if you want to check those out. We are gonna work on getting H264 in next.

thanks for the patience!

**Comment by kc5nra** [comment]
@deepch @colek42 
https://github.com/pions/webrtc/pull/30

**Comment by kc5nra** [comment]
Fixed by https://github.com/pions/webrtc/pull/30

**Comment by cedricve** [comment]
@Sean-Der  any examples of sending a local RTSP stream to the browser? Heavily interested.

Amazing work ;)

**Comment by backkem** [comment]
@cedricve https://github.com/deepch/RTSPtoWebRTC may help you on your way.
