### ISSUE TITLE
Implement RTCP handling

### ISSUE THREAD

**Issue by Sean-Der** [pions/webrtc#119]
This can be broken into smaller issues, but at a high level we need to allow users to send RTCP packets to an RTCPeerConnection. Right now we are unable to build an SFU because when a new peer joins a room we can't send a FIR

This is what we need
* Create a new package `pkg/rtcp` that has structs for all the different RTCP Packet types
* I should be able to `Pack` and `Unpack` into these struct
* I should be able to parse a `[]byte{}` and get a `Packet` back
* Tests that assert this all works

This should closely model the `pkg/rtp` package

**Comment by Sean-Der** [comment]
This has landed!

The `sfu` example shows how to send RTCP. Further improvements can just keep rolling in as we go.

**Comment by wdouglass** [comment]
I'm currently working on some infrastructure for the application to receive RTCP messages as well -- i'll submit a pull request later today.

**Comment by Sean-Der** [comment]
That would be awesome @wdouglass looking forward to the contribution!

**Comment by wdouglass** [comment]
It was a little buggier then I expected, hopefully the pull request will
come earlier next week
