### ISSUE TITLE
Mobiles

### ISSUE THREAD

**Issue by gedw99** [pions/webrtc#12]
So can I run this on a mobile ? I guess not since it wants gstreaner for the real time transcode ?

**Comment by Sean-Der** [comment]
Hey @gedw99!

This will 100% run on mobile. GStreamer is just in the examples to show how one could either generate (or display) video using GStreamer. I am also going to do a ffmpeg example.

But there is no requirement that you use GStreamer in your application. If you are up for it would love doc updates that makes it clear. It is just hard for me, I assume people know whats in my head.

thanks.

**Comment by gedw99** [comment]
by doc updates you mean documenation about how to use the code in this repo ? I think you mean something else though - maybe about using gomobile and cross compiling to mobile.

anyway i doubt ffmpeg can be used compiled in to work on gomobile. Its not like how on desktop you can use a c import. But there are ways.

I think you should checked this github org !
https://github.com/xlab

He is really into golang and using c libs for video and graphics.. There is some useful stuff here i feel for this project.

**Comment by Sean-Der** [comment]
Documentation about anything would be great! Happy to give you access to create a wiki if you want, it doesn't have to be perfect but the more people involved the better :)

You don't need to use ffmpeg either. pion-WebRTC just emits/takes `[]byte` there is no requirement to use GStreamer, ffmpeg (or anything else) those examples are just to help people who already use those things.

Those are some cool projects! Especially the libvpx one, thanks for sharing.

**Comment by gedw99** [comment]
Check this out !

https://github.com/cloudwebrtc/flutter-webrtc/issues/5#issuecomment-401592449

Flutter is an excellent choice for the GUI and supports mobile and desktop with no changes.

It has support for camera capture and screen capture today.

A webrtc plugin for the flutter GUI can be written in golang and would work really well.

So the above link is a backline to another group looking to use flutter for webrtc. Nice common goals !!!!

I use flutter with golang. It's pretty cool because you get you stuff running everywhere and in very high quality. On old mobiles it works better than native I have found. Hard to believe I know and it's subjective. I was surprised myself.

For example I use a golang plugin to do jsonrpc between the flutter GUI and anything I need to run inside flutter like databases, business logic, anything.

You can also do grpc between flutter and golang.

**Comment by Sean-Der** [comment]
Moved into roadmap (added entry for mobile support)
