### ISSUE TITLE
Examples: Serve fiddles locally

### ISSUE THREAD

**Issue by Sean-Der** [pions/webrtc#120]
We should run a local HTTPS server so people don't even need to open a jsfiddle. This will also allow people to prototype faster using tools they are already comfortable with.

**Comment by backkem** [comment]
I've also been toying with the idea to make the examples serve as integration tests. The downside is that it likely requires a bit of test specific code in the examples which may reduce clarity. There may be some clever ways to hide this thought. The advantage would be that we don't need to duplicate all this code for the integration tests.
