### ISSUE TITLE
Remove global state from DTLS package

### ISSUE THREAD

**Issue by Sean-Der** [pions/webrtc#133]
Currently DTLS package has un-needed global state

**Problems**
Because we are currently using openssl based dtls that is in c we are forced to use cgo to integrate with it. cgo comes with its own challenges and because of it two separate issues arise to the top. The first one is that we have to create separate global data structures to allow openssl to send out messages into the world. The second has to do with the way openssl operates. Under the hood open ssl writes output messages into an internal buffer or file descriptor depending on how open ssl is setup. Using `SSL_set_fd` or `SSL_set_bio`. Because of that the current implementation does synchronous calls to check if the buffer is full and sends out the data via the exported global golang objects.

**Proposals**
There are currently two proposals on the table. One is in favor of adding a blocking queue on the c side which go functions could query via separate goroutines and clean out the outbound messaging buffers. 

An alternative to that is instead, of calling a go callback to send the packets (as it is set up current), return the out buffer to the caller (and they can send) it means we don't have to store sockets twice anymore!

**Comment by trivigy** [comment]
@Sean-Der I am really worried about the choice "shying away from extra c code at all costs" at the cost of faulty current design. I agree we should be moving to a native dtls. Unfortunately that is a huge project undertaking that we are not going to complete for a while. In the meantime there might be a real issue with the dtls not able to send out all of the buffer messages it generates. The entire openssl library was design with the idea of sink in mind. That is why the two functions that set up the session are `SSL_set_fd` or `SSL_set_bio` and in both cases the create in/out channels.

**Comment by Sean-Der** [comment]
@trivigy the DTLS code right now matches mediasoup+Janus, and neither of them have any issues around this.

**Comment by trivigy** [comment]
@Sean-Der Those projects implement a callback to golang which is needed to be global.

**Comment by trivigy** [comment]
@Sean-Der unfortunately this design issue is blocking me. Any chance we can somehow come to a decision on this one?

**Comment by trivigy** [comment]
http://roxlu.com/2014/042/using-openssl-with-memory-bios following this example it looks like with BIO in memory buffers the output can be completely exported at the right moments. So we can implement the solution you described. The one element that will be missing is `SSL_set_info_callback()`. Instead I am going to export the state together with the buffer after each call to the external library. This way we can completely remove the global callbacks and global state variables. @Sean-Der

**Comment by Sean-Der** [comment]
Janus is C, mediasoup is C++ neither of those projects have Go.

I would split this up into two commits first have those functions return buffers, that removes all your global state and we can be confident that everything works.

`SSL_set_info_callback` looks to only be useful for alerts, so I would put an atomic on the SSL session and then query it. That should be really maintainable https://github.com/meetecho/janus-gateway/blob/master/dtls.c#L929

**Comment by Sean-Der** [comment]
I am working on Go native DTLS in #204 won't be doing any work with OpenSSL
