### ISSUE TITLE
Datachannels are not working

### ISSUE THREAD

**Issue by Bogdan-D** [pions/webrtc#153]
I saw that api-datachannels branch was merged, decide to try how does it working. The problem is there nothing is happened when I'm creating new datachannel, not from js nor from golang.
Also examples are not go gettable, I suggest it's outdated
```
C:\Users\user\Documents>go get github.com/pions/webrtc/examples/data-channels
# github.com/pions/webrtc/pkg/ice
Go\src\github.com\pions\webrtc\pkg\ice\agent.go:132:5: undefined: stun.UseCandidate
Go\src\github.com\pions\webrtc\pkg\ice\agent.go:133:5: undefined: stun.IceControlling
Go\src\github.com\pions\webrtc\pkg\ice\agent.go:134:5: undefined: stun.Priority
Go\src\github.com\pions\webrtc\pkg\ice\agent.go:144:5: undefined: stun.UseCandidate
Go\src\github.com\pions\webrtc\pkg\ice\agent.go:145:5: undefined: stun.IceControlled
Go\src\github.com\pions\webrtc\pkg\ice\agent.go:146:5: undefined: stun.Priority
```

**Comment by Sean-Der** [comment]
Hey @Bogdan-D I think your copy of `github.com\pions\pkg` is out of date.

Can you try `go get -u github.com/pions/webrtc/examples/data-channels` that should auto-update all dependencies.

thanks!

**Comment by Bogdan-D** [comment]
Got what's wrong, openssl dll files was missing. Doub't how it was working with regular streaming :)
