### ISSUE TITLE
DataChannel open message missing

### ISSUE THREAD

**Issue by Bogdan-D** [pions/webrtc#159]
In current webrtc state dataChannel working only if they are opened from javascript.
Datachannel open from golang does nothing (even when I call `SendOpenChannelMessage` manually), also manual negoitaion is not possible

**Comment by backkem** [comment]
Yes, you are correct. We are actively working on filling these gaps in our implementation.

In the mean time: The ``data-channels-create`` example has a workaround for this that works with Chrome. (In my testing it doesn't work when connecting to NodeJS thought). On [main.go#L42](https://github.com/pions/webrtc/blob/master/examples/data-channels-create/main.go#L42) you can see we manually call ``SendOpenChannelMessage`` when the ``ICEConnectionState`` changes to ``Connected``. Again, this is obviously a temporary workaround until we can complete the underlying implementation.

**Comment by Bogdan-D** [comment]
Yeah, I've tried that workaround but without success

**Comment by backkem** [comment]
Hi @Bogdan-D, can you please test again with the last master branch. We're now sending the ChannelOpen messages when creating data channels in Pions. These changes also make Pions to Pions and Pions to NodeJS data channels work in my testing.

**Comment by Sean-Der** [comment]
Thanks for implementing this @backkem  :)

Closing for now, feel free to re-open @Bogdan-D if it is still an issue, thanks!
