### ISSUE TITLE
Implement better SDP builder

### ISSUE THREAD

**Issue by Sean-Der** [pions/webrtc#19]
SDP construction is not great currently. It is a loose collection of SDP methods.  https://github.com/pions/webrtc/blob/master/internal/sdp/util.go#L26

Implement a Go idiomatic way so I can build an SDP given things like
```
IceUsername, IcePassword, Fingerprint string
Candidates []string
Tracks []*SessionBuilderTrack
```

**Comment by notedit** [comment]
what about some api like  https://github.com/ibc/libsdptransform?

**Comment by backkem** [comment]
Some form of [functional options](https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis) may also provide an alternative:
```go
s := NewSession(
	WithName("My session"),
	WithAttributes([]string{
		"key:value",
	}),
)
```

**Comment by Sean-Der** [comment]
@notedit ibc does AMAZING work, you can't go wrong with stuff like that :)

@backkem APIs like that are great! We have something similar, in our [TURN server/client](github.com/pions/turn) and it reads really well.

If either of you are interested making SDP processing better would be a huge improvement. I am just short on time, going all in on DataChannels for the next week or so. If you are up for it I want to add you to the repository and you can start working on a branch right away. Want to make it so people can work as fast as possible/enjoy it.

thanks!

**Comment by notedit** [comment]
Hi @Sean-Der,   i want to pick this. but i  am not so  self-confidence on my golang skills and only have 1-2 free hours  one day.    i will  try this on my private repo.  
Thanks.  If others can just do this right away,   please do.

**Comment by backkem** [comment]
@notedit do you intend on adding the JSON or functional options? They don't have to be exclusive. The idiomatic way to add JSON suppprt is probably to add new Marchall methods.

**Comment by notedit** [comment]
@backkem  I am thinking add some JSON lib.  also add simulcast/svc parser.

**Comment by Sean-Der** [comment]
Hey @notedit no rush at all! Also a great chance to get better at Golang. If you have any questions feel free to reach out :)

**Comment by backkem** [comment]
The functional options API didn't seem scalable enough. I've opted for a chainable API in #35. As an example, this would look as follows: 
```go
d := sdp.NewDescription().
	WithOrigin("-",  1, 2, "IN", "IP4", "0.0.0.0").
	WithSessionName("-").
	WithPropertyAttribute("sendrecv").
	WithValueAttribute("ice-options", "trickle")
```

PR #35 only implements the chainable API within the context of [JSEP](https://tools.ietf.org/html/draft-ietf-rtcweb-jsep) for now. However, It should be easy to generalize.

@notedit Don't let this distract you. JSON marshaling would still be a great addition.

**Comment by notedit** [comment]
@backkem  That looks great,  I will try do the first version and then optimize the API.

**Comment by notedit** [comment]
I have already made a working sdp-transform like lib  here  https://github.com/notedit/go-sdp-transform.  It just is sdp to json,  json to sdp.
I am not sure about the SDP builder,  @Sean-Der  do you have any advise about this? 
What i want to do is something like https://github.com/medooze/semantic-sdp-js,  the api is great.

**Comment by notedit** [comment]
It  seems  @backkem  already did this.  

I write a golang sdp transform lib here   https://github.com/notedit/go-sdp-transform.

**Comment by backkem** [comment]
@notedit I only did the minimal SDP generation/parsing needed for my initial offer/answer implementation. Most of it is in jsep.go. There is definitely room for improvement:
1. Complete the API to support the entire SDP spec.
1. The parsing currently mostly returns entire lines. It would be nice to have direct access to every individual value. This will definitely help for further improvements of the offer/answer procedure. Right now, additional parsing is done in an ad-hoc way when needed but it would be better if it was more well structured.

**Comment by backkem** [comment]
Closing due to @trivigy's great work on the SDP builder and parser.
