### ISSUE TITLE
gstreamer-send /dev/video (webcam)

### ISSUE THREAD

**Issue by projetoarduino** [pions/webrtc#193]
Hi

Is possible in my linux system send via webrtc with to source /dev/video (webcam)

**Comment by kc5nra** [comment]
Yeah! Just switch out the gstreamer-send example to use v4l2src using /dev/video path

**Comment by Sean-Der** [comment]
Hey @projetoarduino 

That should be really easy! Replace `videotestsrc` with any source you want [here](https://github.com/pions/webrtc/blob/master/examples/gstreamer-send/gst/gst.go#L37-L48). On Linux you can replace with `autovideosrc` and it should work out of the box.

If that works feel free to close the ticket! Also feel free to join the Slack channel, we are all active on there and happy to help with anything.

**Comment by Sean-Der** [comment]
You can also experiment with GStreamer pipelines locally using `gst-launch-1.0` which is a great way to prototype pipelines before using them in code.

**Comment by Sean-Der** [comment]
Hey @projetoarduino I am closing the issue for now, feel free to reopen if you have any questions!

thanks

**Comment by projetoarduino** [comment]
Hi thanks for help me.

I made the modifications, and change  autovideosrc in gst.go.

But when i running in my linux board arm (h3 board) with webcam the streaming in very very slow, is exist one way to improviment this performance

**Comment by Sean-Der** [comment]
Is it constrained by CPU usage?

I am not positive, but it looks like that supports H264 hardware encoding, try to use that with GStreamer. WebRTC supports H264, so still should work great! You can just do `gst-launch videotestsrc is-live=true ! vp8enc ! fakesink` then you can test CPU usage `vp8enc` vs others encoders. 

You can also try lowering the resolution/encoding quality of VP8. I would assume the majority of the CPU usage is from video operations.

Also try the DataChannels example, and compare the CPU usage might help with some basic benchmarking!

**Comment by projetoarduino** [comment]
Hi guys 

This line work well

pipelineStr = "v4l2src device=/dev/video0 ! videoconvert ! video/x-raw,format=I420,width=320,height=240 ! vp8enc end-usage=cbr cpu-used=5 threads=4 target-bitrate=2048 max-quantizer=40 min-quantizer=10 cq-level=10 ! " + pipelineStr

My processor allwinner h3 only consum 50% of system

Another question please :)

i want capture mic from this board and send via webrtc any idea ?
