### ISSUE TITLE
Port DTLS code to Native Go (instead of OpenSSL)

### ISSUE THREAD

**Issue by Sean-Der** [pions/webrtc#20]
This is a huge task, but if someone is up for it I won't stop them :)

When I get around to this I will assign to myself and start the long task. Also more then happy to split the task/get guidance if you are familiar with DTLS/have opinions on how the API looks but don't have time to do the coding.

**Comment by nicolai86** [comment]
The relevant RFC for this is [RFC 6347](https://tools.ietf.org/html/rfc6347) , correct?

**Comment by backkem** [comment]
Yes, there's also an overview of RFCs on the [wiki](https://github.com/pions/webrtc/wiki/Relative-Drafts-And-Usages).

**Comment by gedw99** [comment]
There is an existing DTLC golang implementation..

Background:
The go team have an issue for a pure golang dtls implementation:
https://github.com/golang/go/issues/13525
But they are still holding out from putting a go team supported package into the go crypto library.

In that issue, the most promising DTLS implementation highlighted is this:
https://github.com/bocajim/dtls

@bocajim  @backkem 

Sounds like there is some strong synergy here to get this done ?

@bocajim: Your code says it implements RFC-4347, and the webrtc team have said they need RFC-6347 ( see the wiki page at https://github.com/pions/webrtc/wiki/Relative-Drafts-And-Usages#dtls ).

**Comment by Sean-Der** [comment]
I moved this to our [Project Ideas](https://github.com/pions/webrtc/wiki/Contributing#project-ideas)

**Comment by gedw99** [comment]
@Sean-Der 
there are many good c DTLS, and so maybe a conversion like what the golang team often do. For example when they had to charge the compiler itself from c to go.

https://github.com/elliotchance/c2go

**Comment by trivigy** [comment]
@gedw99 Did you end up trying the c2go route?
