### ISSUE TITLE
Gateway for NATS

### ISSUE THREAD

**Issue by gedw99** [pions/webrtc#201]
It would be pretty useful to make a webrtc gateway for NATS.

This seems safest to ensure messages don't get lost due to network issues.

https://github.com/isobit/websocket-nats
- so web browser client works on ALL browsers 

https://github.com/orus-io/nats-websocket-gw
- so web browser has server.

Need to write my a NATS to webrtc code gateway from the above examples.

**Comment by thetooth** [comment]
I have found wrapping or embedding the peer connection and datachannel(s) into your own struct type to hold information about the session as a whole works quite well. You can then have both the peercon and datachannel callbacks pointing to methods that are part of this type. Then it's as simple as dropping your pub/sub call logic inside OnMessage.

**Comment by gedw99** [comment]
Have you got an example on GitHub by any chance ?

I gotta admit I am quite impartial to NATs because I can build little blocks of functional code and just let them interact via NATS with webrtc is the Comms up above to all the clients 
But your example would be useful for the gateway between the client and NATS using the webrtc transport

**Comment by thetooth** [comment]
```go
func New(natsConn *nats.Conn, pc *webrtc.RTCPeerConnection) *Subscription {
	sub := &Subscription{
		nc:             natsConn,
		PeerConnection: pc,
	}
	// Set the handler for incoming datachannels
	pc.OnDataChannel = sub.OnDataChannel

	return sub
}

type Subscription struct {
	PeerConnection *webrtc.RTCPeerConnection
	DataChannel    *webrtc.RTCDataChannel

	nc *nats.Conn
}

func (s *Subscription) OnDataChannel(d *webrtc.RTCDataChannel) {
	log.Info("On Datachannel")
	d.Lock()
	defer d.Unlock()

	if s.DataChannel == nil {
		s.DataChannel = d
		// Set the handler for incoming messages
		s.DataChannel.Onmessage = s.Onmessage
	}
}

func (s *Subscription) Onmessage(payload datachannel.Payload) {
	p := payload.(*datachannel.PayloadString)

	log.Infof("Relaying '%s' payload '%s'", s.DataChannel.Label, string(p.Data))

	if err := s.nc.Publish("webrtc."+s.DataChannel.Label, p.Data); err != nil {
		log.Error(err)
	}
}
```
Should do it.

**Comment by Sean-Der** [comment]
Hey @gedw99 closing this for now since the pion-WebRTC developers can't act upon this.

I would love to see a wiki article with all these ideas you are having though. I think it could be really inspiring, I would also love to see all the projects you think we should approach! Every time I stumble upon a cool Golang project I notice you are already there :)

**Comment by gedw99** [comment]
Hey Sean,

Yeah I am a bit promiscuous :)

I got NATS and webrtc working. Thanks @thetooth. Really nice approach.

Now I am deeply looking into webrtc for video streaming to non web browsers. Doing it with web browsers is pretty easy and s ton examples out there as we all know.
But for desktop and mobile I could just embed chrome and use that and a webview but I don't want that baggage. I want intimate control to do unique things.
So I was looking into gstreamer and it now ( recently ) has webrtc support. The biggest hurdle to overcome is to capture the users video cam and feed that into gstreamer so all the heavy work is done with gstreamer using the house and the codecs baked into gstreamer. Not doing this approach results in crappy perf ( maybe 5 FPS ).
Then for your display window just a matter of taking into the output and using GL to render the output to a window.

Then one that's working I was looking into what is going on with real time mixing and broadcasting systems. You can use webrtc but for big boy stuff in the broadcast industry there are completely different protocols for the output.
The mixing desk uses webrtc because that's clearly smart.
But your input and outputs from the mixer is broadcast industry codes and packet stuff.
This would allow don't cameras with a laptop and mobile phone ( for data connection ) to stream live events in, and then get mixed in the mixing desk ( webrtc based GUI ) and output to other reviewers. 
The BBC have built an open source one that is the same architecture as above but it's python so forget it :) but I think it shows just how powerful gstreamer is now and it's just a matter of tapping into it via he golang bindings and playing around.

The mixing desk once done of course can be setup with scenarios for multi party conferencing with all parties just using webrtc inputs and outputs.
The broadcast industry codes and packet stuff would reuse the mixing desk .I noticed there is a mini revolution going on:

AV1 is agreed by the open players now .

The broadcast industry has agreed on an open protocol too and has Apple, Google, Microsoft backing.

So stars are aligning as they say 

If anyone has thoughts on this do holler !!!
I am particularly interested in broadcast industry codecs and packet streaming norms and future directions.
