### ISSUE TITLE
Can I use pions-webrtc in concurrency environment?

### ISSUE THREAD

**Issue by Hixon10** [pions/webrtc#202]
Hello,

I have some questions about concurrency in this project:

Should I create a new ```RTCDataChannel``` each time, when I want to send some bytes from one pion to another one? I mean, I want to send bytes from pion1 to pion2 and from pion1 to pion3 simultaneously. Should I in that case to create two different ```RTCDataChannels``` (like, ```webrtc.New(config)```), or should I have one ```RTCDataChannels``` per application?

Also, if you have some concurrency model for this project (like, some object is not thread safe and so on), I will be happy to get it.

Thanks, folks.

**Comment by gedw99** [comment]
Have to say that NATS would get you that concurrency.
I raised an issue already about this

**Comment by Sean-Der** [comment]
Hey @Hixon10 

You should create a unique `RTCDataChannel` for each DataChannel you want to open (like `webrtc.New`). I will update docs/add and error if you try to reuse to make it more user friendly, thanks for pointing that out.

Also will update the docs around what needs to be locked/unlocked. Everything in the examples should be thread safe, so if you find something with `-race` when following the examples that is a bug! 

I will keep this issue open and close out when I fix this stuff, thanks

**Comment by Hixon10** [comment]
@Sean-Der  Thank you!

**Comment by Sean-Der** [comment]
Hey @Hixon10 

We updated the API so users don't have to take locks when setting things.

We also added `E2E` tests that run with `-race` and things seem to be working pretty well. If you have any suggestions I would still love to improve things, but it seems to be working ok so far.

Thanks again for using pion-WebRTC! Really excited to see people using it
