### ISSUE TITLE
Implement Go native DTLS out of tree

### ISSUE THREAD

**Issue by Sean-Der** [pions/webrtc#204]
I am working on a Go native DTLS implementation [here]( https://github.com/sean-der/dtls)

It is only going to support the cipherSuites/extensions needed for DTLS so should be very small compared to other solutions. It needs the following features before it can be imported.

* [x] Implement retransmissions/timeouts
* [x] Implement `use_srtp`
* [x] Implement `TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA` and `TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256`

----

If anyone is interested would love to work together also. I am also happy to consider making this an external package if others are willing to work on it also, but not going to put the effort forward otherwise.

**Comment by aguilEA** [comment]
Hey @Sean-Der I can help with the native Go implementation of DTLS. Are you already working on one of the features?

**Comment by Sean-Der** [comment]
This is done! We are working on using our DTLS 1.2 implementation now.
