### ISSUE TITLE
gstreamer-send from file not working

### ISSUE THREAD

**Issue by SriramScorp** [pions/webrtc#206]
I'm running the examples on my local machine. I modified the pipeline in the gst.go file to stream from a filesrc but I can't find a way to make it work. I keep seeing only the videotestsrc on the browser end. I confirmed the pipeline works fine on the command line. What am I missing?

**Comment by Sean-Der** [comment]
Hey @SriramScorp 

Mind sharing a diff? Are you changing the [VP8 branch](https://github.com/pions/webrtc/blob/master/examples/gstreamer-send/gst/gst.go#L39) ? The example uses VP8 by default

**Comment by SriramScorp** [comment]
Yes. I am aware that the example uses vp8 by default and am modifying the vp8 pipeline. I changed the pipeline in the gst.go file to read as below and compiled the go file. 

       case webrtc.VP8:
                pipelineStr = "filesrc location=/tmp/big_buck_bunny.mp4 ! decodebin ! videoscale ! 'video/x-raw,width=640,height=480' ! videorate ! videoconvert ! timeoverlay ! vp8enc ! " + pipelineStr

When I change the patterns in videotestsrc and compile, they work fine. But, filesrc still shows videotestsrc with moving ball. Should I be registering any other webrtc codes? Thanks for further help.

**Comment by Sean-Der** [comment]
Hey @SriramScorp 

Sorry for the late response, but you can now stream a file using the `gstreamer-send` example without any modifications! You can see it [here](https://github.com/pions/webrtc/tree/master/examples/gstreamer-send#customizing-your-video-or-audio)

Sorry this took so long, the DTLS implementation, really took up a lot of time. If there is anything else I can do always happy to help
