### ISSUE TITLE
Firefox (> 63) mediadescription fmt = webrtc-datachannel

### ISSUE THREAD

**Issue by wezzle** [pions/webrtc#208]
This triggers the following error: `sdp: invalid numeric value webrtc-datachannel` on line: https://github.com/pions/webrtc/blob/c7f838b98d7a5bdab8578764f79bb847d895f000/internal/sdp/unmarshal.go#L839

See https://blog.mozilla.org/webrtc/how-to-avoid-data-channel-breaking/

Firefox now sends the data channels as followed:
```
m=application 54111 UDP/DTLS/SCTP webrtc-datachannel
a=sctp-port:5000
```

I've tried finding out where in the code base this could be changed but I couldn't find any reference to `sctp-port` or the old syntax `sctpmap:5000` except for the static line: https://github.com/pions/webrtc/blob/c7f838b98d7a5bdab8578764f79bb847d895f000/rtcpeerconnection.go#L937

I'm happy to help but I'm afraid I lack the protocol knowledge to make a valid pull request.

**Comment by Sean-Der** [comment]
Hey @wezzle @Lesterpig sorry for the delay! We just removed the OpenSSL dependency so moving back through tickets. I should be able to take a crack at this tomorrow (and should be pretty quick)

If either of you would like to contribute also would be happy to help review/offer guidance :) Feel free to join the Slack and happy to talk anytime!

thanks
