### ISSUE TITLE
Send and receive in one session

### ISSUE THREAD

**Issue by projetoarduino** [pions/webrtc#209]
Hi i need help or one example to send audio and video in golang to receive on my browser and send back my mic capture to golang.

Anyone please.

**Comment by Sean-Der** [comment]
Hey @projetoarduino can you post what you have tried so far?

We don't have an example currently, but I would be against making something with GStreamer (maybe you upload video and we add text effects or something like that?)

**Comment by projetoarduino** [comment]
Hi thanks for reply

This code send and receive audio but dont send video

`package main

import (
	"fmt"
	"io"
	"os"

	"bufio"
	"encoding/base64"

	"github.com/pions/webrtc"
	"github.com/projetoarduino/gstTX"
	"github.com/projetoarduino/gstRX"
	"github.com/pions/webrtc/pkg/ice"
)

func main() {
	reader := bufio.NewReader(os.Stdin)
	rawSd, err := reader.ReadString('\n')
	if err != nil && err != io.EOF {
		panic(err)
	}

	fmt.Println("")
	sd, err := base64.StdEncoding.DecodeString(rawSd)
	if err != nil {
		panic(err)
	}

	/* Everything below is the pion-WebRTC API, thanks for using it! */

	// Setup the codecs you want to use.
	// We'll use the default ones but you can also define your own
	webrtc.RegisterDefaultCodecs()

	// Create a new RTCPeerConnection
	peerConnection, err := webrtc.New(webrtc.RTCConfiguration{
		IceServers: []webrtc.RTCIceServer{
			{
				URLs: []string{"stun:stun.l.google.com:19302"},
			},
		},
	})
	if err != nil {
		panic(err)
	}

	// Set the handler for ICE connection state
	// This will notify you when the peer has connected/disconnected
	peerConnection.OnICEConnectionStateChange = func(connectionState ice.ConnectionState) {
		fmt.Printf("Connection State has changed %s \n", connectionState.String())
	}

	// Create a audio track
	opusTrack, err := peerConnection.NewRTCTrack(webrtc.DefaultPayloadTypeOpus, "audio", "pion1")
	if err != nil {
		panic(err)
	}
	_, err = peerConnection.AddTrack(opusTrack)
	if err != nil {
		panic(err)
	}

	// Create a video track
	vp8Track, err := peerConnection.NewRTCTrack(webrtc.DefaultPayloadTypeVP8, "video", "pion2")
	if err != nil {
		panic(err)
	}
	_, err = peerConnection.AddTrack(vp8Track)
	if err != nil {
		panic(err)
	}

	// Set a handler for when a new remote track starts, this handler creates a gstreamer pipeline
	// for the given codec
	peerConnection.OnTrack = func(track *webrtc.RTCTrack) {
		codec := track.Codec
		fmt.Printf("Track has started, of type %d: %s \n", track.PayloadType, codec.Name)
		pipeline := gstRX.CreatePipeline(codec.Name)
		pipeline.Start()
		for {
			p := <-track.Packets
			pipeline.Push(p.Raw)
		}
	}

	// Set the remote SessionDescription
	offer := webrtc.RTCSessionDescription{
		Type: webrtc.RTCSdpTypeOffer,
		Sdp:  string(sd),
	}
	if err := peerConnection.SetRemoteDescription(offer); err != nil {
		panic(err)
	}

	// Sets the LocalDescription, and starts our UDP listeners
	answer, err := peerConnection.CreateAnswer(nil)
	if err != nil {
		panic(err)
	}

	// Get the LocalDescription and take it to base64 so we can paste in browser
	fmt.Println(base64.StdEncoding.EncodeToString([]byte(answer.Sdp)))

	// Start pushing buffers on these tracks
	gstTX.CreatePipeline(webrtc.Opus, opusTrack.Samples).Start()
	gstTX.CreatePipeline(webrtc.VP8, vp8Track.Samples).Start()
	select {}
}`

**Comment by Sean-Der** [comment]
Hey @projetoarduino 

Really sorry about how long this took, I was working on the DTLS stuff and got overloaded :/

I updated the `gstreamer-src` example so you can send your webcam directly from it. You can see that [here](https://github.com/pions/webrtc/tree/master/examples/gstreamer-send#customizing-your-video-or-audio)

I would modify the `gstreamer-send` example and just add a call to `peerConnection.OnTrack(func(track *webrtc.RTCTrack) {` and if the other send is offering any media tracks it will appear there.

If you are stuck we would love to have you on Slack! You can find it in the README, you will be able to get help from multiple people in the community. I tend to be pretty bogged down, but will try my best.

**Comment by projetoarduino** [comment]
hey @Sean-Der 

Thank you very much for remembering my case.

I have already updated the lib, and I have a prototype code in hand.

I can send audio and video receive audio, I have already created an app for android and a signaling server.

I want to thank you for your excellent work and I am willing to help you with what is needed.

**Comment by Sean-Der** [comment]
Of course @projetoarduino 

we are all super grateful that you are using pion-WebRTC. The team puts a lot of time and effort into it, so makes me really happy that people actually like it :) Thanks again for the patience

Enjoy the new years

**Comment by conanchen** [comment]
> hey @Sean-Der
> 
> Thank you very much for remembering my case.
> 
> I have already updated the lib, and I have a prototype code in hand.
> 
> I can send audio and video receive audio, I have already created an app for android and a signaling server.
> 
> I want to thank you for your excellent work and I am willing to help you with what is needed.

Hello @projetoarduino 

do you use pion/webrtc in android app? 
if so, may you share the android app snippet code with pion/webrtc part?
