### ISSUE TITLE
Allow user to pass supported codecs

### ISSUE THREAD

**Issue by Sean-Der** [pions/webrtc#22]
I don't know exactly what this will look like API wise but we should allow users to specify what codecs they support. This is needed to support cases where user doesn't support all codecs (has hardware decoder for only some codecs)

* Update RTCPeerConnection to allow user to pass supported codecs
* Update SDP generation to take this into account. Also error if user creates a track for a codec we don't support.

**Comment by backkem** [comment]
#35 introduces the ability to register codecs. By default you can register a codec with the default media engine. This media engine is used by all new peer connections. However, the user can create a custom media engine and assign it to one or more peer connections.
Are there any more options we should address within the scope of this issue or do we close it and create new issues if needed?
