### ISSUE TITLE
Add logging to RTCPeerConnection

### ISSUE THREAD

**Issue by aguilEA** [pions/webrtc#222]
RTCPeerConnection should have a logger to debug SDP/Packets and to log other messages at varying verbose levels. RTCPeerConnection should accept an interface so that a user can customize a logger and pass the logger to RTCPeerConnection through a setter. This logging implementation can begin with a simple default logger that will replace all the fmt.print and fmt.printf messages that are currently in rtcpeerconnection.go.

**Comment by backkem** [comment]
Basic logging support has been added in #360.
