### ISSUE TITLE
Implement full ICE

### ISSUE THREAD

**Issue by Sean-Der** [pions/webrtc#23]
Currently we only implement `ice-lite` we need to finish this so we can operate with other peers that are `ice-lite` only.

* We should be able to respond to DTLS handshakes (currently we always generate them)
* We should generate the STUN requests to check for ICE connectivity (instead of only responding to them)
* Accept the first connected peer

----
The full RFC is [here](https://tools.ietf.org/html/draft-ietf-ice-rfc5245bis-20) you don't have to implement it fully, just enough so we have an MVP. Then we can keep improving it. It is a big RFC

**Comment by chenkaiC4** [comment]
Draft is here: https://tools.ietf.org/html/rfc5245#section-2.7

**Comment by chenkaiC4** [comment]
Hi, @Sean-Der , i'm read ICE draft, and want to try solve this issue. I will give a PR as soon as possiple.

**Comment by Sean-Der** [comment]
@chenkaiC4 That would be fantastic!

I am also on Slack so anytime you want to chat I am available. This will be great when we get the Wiki  started also. I am setting some stuff up but will also add it so you can create branches on this repo, I want everyone to be able to push/work on code together. 

Hopefully great less friction, and make it more enjoyable to contribute :)

**Comment by chenkaiC4** [comment]
@Sean-Der thanks, 🥂

**Comment by Sean-Der** [comment]
Hey @chenkaiC4 now that DataChannels dropped I have time to work on this!

If you started working already I would love to work together on it. If you haven't had time no worries at all I have time to grab it now :)

**Comment by Sean-Der** [comment]
@chenkaiC4 no worries at all!

When ever you are ready to contribute would love to have you, we are all on Slack also if you ever need help finding a good issue.

----

This was implemented by https://github.com/pions/webrtc/pull/56
