### ISSUE TITLE
RTCPeerConnectionState stuck at 'new'

### ISSUE THREAD

**Issue by tobiasfriden** [pions/webrtc#230]
Hello, and thanks for the awesome library!

I am trying to implement a SFU using Gstreamers recent webrtc plugin as one client and a browser as the other. Just sending directly p2p from gstreamer to browser works fine, however when putting pions 'in the middle' I am having some issues.

Basically I am trying to setup a connection between Gstreamer client and a pions based server. The server should only recieve a track from the Gstreamer client and forward to browser client.
Sdp exchange between client and server seems to work fine, as well as sending ICE candidates from client and adding to the server side `RTCPeerConnection` using `AddIceCandidate`. Using the `OnICEConnectionStateChange` callback I can also see that ICE state is changing to `connected`.

However, the `onTrack` callback is never triggered. Also, when I added a callback function to print the `RTCPeerConnectionState` of my connection I can see it never changes from `new`.

Am I missing something obvious, or any pointers to how I can try to debug the issue?
Any help greatly appreciated!

**Comment by backkem** [comment]
Hi, It seems we're only setting ´´RTCPeerConnectionStateNew´´ and ´´RTCPeerConnectionStateClosed´´ for now. Sorry about this, we've implemented more enums/structs than are wired up in the logic.

Regarding the OnTrack: Have you registered a codec that matches with the one Gstreamer uses? Normally a warning should be printed if this is not the case thought.

**Comment by tobiasfriden** [comment]
Ok, thanks for the response!

I registered codecs using `webrtc.RegisterDefaultCodecs()` in my main function. The client should send VP8 encoded video.

Here is the exchanged SDPs if that is helpful:

Client offer:
v=0
o=- 7797371982932634147 0 IN IP4 0.0.0.0
s=-
t=0 0
a=ice-options:trickle
a=msid-semantic:WMS sendrecv
m=video 9 UDP/TLS/RTP/SAVPF 97
c=IN IP4 0.0.0.0
a=setup:actpass
a=ice-ufrag:czFgJ5XrXyvI153UQG2iIH6vkpOk5BAt
a=ice-pwd:65uMV3Cs92WZWa9w4p+oZoCSZgv3ToYa
a=sendrecv
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:97 VP8/90000
a=rtcp-fb:97 nack pli
a=framerate:30
a=ssrc:4241793047 msid:user4176533341@host-6b2859db webrtctransceiver0
a=ssrc:4241793047 cname:user4176533341@host-6b2859db
a=mid:video0
a=fingerprint:sha-256 B3:E2:4B:B0:80:F5:B6:44:A3:8C:AC:B9:D1:72:26:09:B9:A5:02:40:0E:4E:14:06:C7:95:33:6F:56:98:20:BD

Server answer:
v=0
o=- 835669690 1542412610 IN IP4 0.0.0.0
s=-
t=0 0
a=fingerprint:sha-256 DF:25:CC:82:C4:BF:80:40:6F:CB:4B:55:41:13:FC:76:54:A4:66:91:CC:77:36:13:65:3A:93:56:FA:42:5C:CF
a=group:BUNDLE video0
m=video 9 UDP/TLS/RTP/SAVPF 96 100 98
c=IN IP4 0.0.0.0
a=setup:active
a=mid:video0
a=ice-ufrag:eofQaSDxPUZBLTHC
a=ice-pwd:gsyXkFTQmoJNAlYKRMyGARzlaBXwAgXF
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtpmap:100 H264/90000
a=fmtp:100 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtpmap:98 VP9/90000
a=recvonly
a=candidate:udpcandidate 1 udp 9138 172.18.0.2 41232 typ host generation 0
a=candidate:udpcandidate 2 udp 10248 172.18.0.2 41232 typ host generation 0
a=candidate:udpcandidate 1 udp 62372 83.254.212.194 59119 typ srflx raddr 172.18.0.2 rport 34436 generation 0
a=candidate:udpcandidate 2 udp 39424 83.254.212.194 59119 typ srflx raddr 172.18.0.2 rport 34436 generation 0
a=end-of-candidates

**Comment by tobiasfriden** [comment]
Update: error found. 
I was sending an offer from the client but calling `setRemoteDescription` on the server with type `webrtc.RTCSdpTypeAnswer`. Closing the issue!
