### ISSUE TITLE
SDP code should be able to generate offers, not only answers

### ISSUE THREAD

**Issue by Sean-Der** [pions/webrtc#24]
Currently we only generate answers. 

The SDP code in general needs a good review. Someone should look at the WebRTC API and make sure we match the Javascript API.

**TODO**
- [x] Implement basic offer generation 
- [x] Create an example of offer generation

**Comment by backkem** [comment]
I'll take a shot at [this](https://w3c.github.io/webrtc-pc/#methods).

**Comment by Sean-Der** [comment]
Fantastic, thanks @backkem !

I will add you to repo, feel free to refactor anything you want while in there! I tend to just shoot for an MVP, so a lot can be improved.

**Comment by Sean-Der** [comment]
This was implemented by https://github.com/pions/webrtc/commit/bf062e38b7b2c8108868cf6aea4b28279b074c32
