### ISSUE TITLE
Dependency management

### ISSUE THREAD

**Issue by backkem** [pions/webrtc#244]
Since the project is becoming bigger and has multiple repositories it may be a good time to start thinking about dependency management. It seems that go modules is getting decent support from the go team and community. How do we feel about adopting this strategy?

**Comment by Sean-Der** [comment]
👍 for me with modules.

I say we tag `dtls` this weekend, and our first release with `go-native` will be with a dtls at `1.0.0`

**Comment by Sean-Der** [comment]
I also vote for moving SRTP out of tree (it has been pretty stable) no rush on that though
