### ISSUE TITLE
Find better way to generate contributors in README.md

### ISSUE THREAD

**Issue by Sean-Der** [pions/webrtc#26]
Currently I am manually updating them, I see other projects have a nice way to credit everyone that has helped. It would be great if someone could implement this so everyone that helps out gets credit :)

**Comment by shoutoutloud** [comment]
Hi.This might be helpful :smiley:
[https://github.com/DavidWells/markdown-magic-github-contributors/blob/master/README.md#1-add-markdown-magic-transform-script](url)

**Comment by Sean-Der** [comment]
Oh that is cool @shoutoutloud !

Yea something like that would be great, in a perfect world it would either just be a shell script or Go. I don't want to add Javascript as a dependency. I might take a crack at this soon, but if anyone else wants it would get merged right away

**Comment by Sean-Der** [comment]
@nicolai86 oh nice that is perfect, I will add a `git push` hook that makes sure people are added!

Also in the future might be cool to extend it to credit people with what features they did/people who helped but not with code.

**Comment by nicolai86** [comment]
We could generate a Changelog based off of commits and probably also issues; but I’m not sure how to track non-code commits consistently ..

**Comment by Sean-Der** [comment]
Implemented a script that will fail the build if any authors are missing in d34d77216b17caa35c7cbbfafaff4236d8960b5d
