### ISSUE TITLE
SRTP Server/client key mismatch + no authorization of recieved messages

### ISSUE THREAD

**Issue by tobiasfriden** [pions/webrtc#261]
When pions is in the server role the keys passed to `CreateContextSRTP` should be reversed. Also the auth tag on recieved SRTP messages should be authenticated.

I'm working on a possible fix and will submit a pull request shortly.

**Comment by tobiasfriden** [comment]
@Sean-Der yep sure! Should I create another PR for the example or add it to this one?

**Comment by Sean-Der** [comment]
I would just create a new PR with your examples you shared in Github. I just want to make sure you get the credit since you did the work!
