### ISSUE TITLE
examples/data-channels does not work

### ISSUE THREAD

**Issue by Abdisalan** [pions/webrtc#262]
<img width="427" alt="screen shot 2018-12-04 at 10 35 53 pm" src="https://user-images.githubusercontent.com/6256142/49488548-18455a00-f815-11e8-911b-f4fd6f976f8f.png">

I connected then when I try to send a message it disconnects. The only thing in the console is "sendChannel has opened". Am I missing anything?

**Comment by Sean-Der** [comment]
Hey @Abdisalan sorry about that!

We just did a massive refactor, and I think I might have introduced a deadlock. Would you mind pulling master and trying again!

If you are still having issues I would love to help debug in our Slack channel. thanks!

**Comment by Abdisalan** [comment]
That fixed it @Sean-Der! Thank you for the prompt response :)

**Comment by Sean-Der** [comment]
Of course! And thank you for using pion-WebRTC hopefully it helps you build something awesome
