### ISSUE TITLE
Re-enable SRTP Auth tag verification

### ISSUE THREAD

**Issue by Sean-Der** [pions/webrtc#270]
This is failing for me with gstreamer-receive disabling for now

**Comment by davidc604** [comment]
@Sean-Der Do you have further context as what might cause the issue with failing the SRTP Auth tag verification? All of a sudden we're running into an issue with this info/error, ```srtp INFO: 2020/10/21 19:00:12 failed to verify auth tag``` And it only occurs with certain type of contents. Thanks!

**Comment by Sean-Der** [comment]
@davidc604 What is the remote peer?

I have had some people report that certain versions of OpenSSL export invalid keying material. They were using Janus I think? They didn't provide further debugging info yet. They switched to BoringSSL and it fixed everything.

Happy to discuss further here or in https://pion.ly/slack I am PST so might be sleeping. But if you mention me in #pion will respond when I wake up :)
