### ISSUE TITLE
[suggestion] some WebRTC knowledge for every issue or a overview introduction

### ISSUE THREAD

**Issue by chenkaiC4** [pions/webrtc#28]
Hi, @Sean-Der, Thanks For U Great Work! We have look for a Go native WebRTC implement long time.

I have see the issues you created for improving this repo. I hope to contribute some code and want to learn some protocol, but i don't know how to start up for there are series of protocols.

So i suggest to have some basic knowledge for current issues you have created, or a overview intruduction of protocols. Even recommend some blogs or posts relative is fine.

**Comment by Sean-Der** [comment]
That's a great idea @chenkaiC4!

Would you be interested in starting a wiki on the pions/webrtc github project? I would be more then happy to fill in stuff/add what I know.

There are a bunch of holes in my knowledge, so would help me as well!

**Comment by chenkaiC4** [comment]
@Sean-Der I glad to do it! 😄

**Comment by Sean-Der** [comment]
I am happy with this!

We now have a developer wiki, and we are slowly expanding it
