### ISSUE TITLE
crasher in rtp.Unmarshal

### ISSUE THREAD

**Issue by maxhawkins** [pions/webrtc#285]
I encountered a panic due to a bounds exception while parsing a malformed RTP packet.

Version: 1.1.1

```
panic: runtime error: slice bounds out of range

goroutine 33 [running]:
github.com/pions/webrtc/pkg/rtp.(*Packet).Unmarshal(0xc00024a000, 0xc0001f6000, 0x1d4c, 0x1d4c, 0x1d4c, 0x0)
        /Users/max/go/pkg/mod/github.com/pions/webrtc@v1.1.1/pkg/rtp/packet.go:98 +0x47d
main.(*Demo).startConn.func3(0xc0000ccaa0, 0x43f9500, 0xc0000b05c0, 0xc0000bc130, 0xc035d87123, 0xc0000be9c0)
        /Users/max/projects/asciirtc/main.go:139 +0x18a
created by main.(*Demo).startConn
        /Users/max/projects/asciirtc/main.go:123 +0x1e0
```

**Comment by wdouglass** [comment]
Looks like this can be fixed by changing headerLength (line 30 of packet.go) from 4 to 12. also, that headerlength constant only seems to be used in Unmarshal, should we move it to function scope?

**Comment by Sean-Der** [comment]
Thanks for finding this @maxhawkins!

I will grab this (write a test will invalid packet + fix)
