### ISSUE TITLE
general: call peerConnection.Close() generates "sctp: failed to read Endpoint closed" 

### ISSUE THREAD

**Issue by aam335** [pions/webrtc#291]
When trying to close, it generates an infinite "sctp: failed to read Endpoint closed"

**Comment by ast** [comment]
Can confirm. When browser closes connection it gets stuck in an endless loop "sctp: failed to read Endpoint closed"

Seems to be here:
https://github.com/pions/webrtc/blob/62708191c4643ed7979c51e4ec6042f77accee60/internal/sctp/association.go#L182

"// TODO: shutdown"

Probably should shutdown :-)

**Comment by ast** [comment]
A quick and dirty fix if you need this working right away is to replace the ```continue``` with a ```break```.

I'm not into the code base enough to know what is the best way to tear down...

**Comment by backkem** [comment]
We're aware of this issue and are actively working on it in #287.

**Comment by ast** [comment]
Perfect!

**Comment by Sean-Der** [comment]
Hey @aam335 @ast 

This should be fixed! Thanks for using pion-WebRTC :) and if there is anything I can do/other issues feel free to reach out here or on Slack.

thanks.
