### ISSUE TITLE
Opus RTP track payload error

### ISSUE THREAD

**Issue by aam335** [pions/webrtc#292]
Rtp.Packet.Raw on opus track contains .Payload data from offset 0 (w/o rtp header) (packet in Packet.Payload contains 12 bytes less from start)

**Comment by Sean-Der** [comment]
Hey @aam335 

Thanks for using pion-WebRTC! I am sorry I don't fully understand the issue. This sounds like your asking the purpose of these two fields? I think `Raw` (which includes header) and `Payload` which is just the body are working properly.

Feel free to re-open the issue with more info! Also more then happy to chat on the pion Slack (you can find the info in the README)

thanks!

**Comment by aam335** [comment]
Raw=RtpOpusPacket[12:]. The problem occurred several times, possibly due to some build issues. I can’t say more precisely, because after go clean it has not been repeated yet.
