### ISSUE TITLE
gstreamer rtp depay drop old packet  frequently

### ISSUE THREAD

**Issue by wattanakorn495** [pions/webrtc#303]
I modified pion-to-pion example to send video from pion peer to another peer 
code here: https://github.com/wattanakorn495/pion-to-pion-video

i got these message from gstreamer debug

> 0:00:25.846099399  2186 0x7fcf7822e450 WARN        rtpbasedepayload gstrtpbasedepayload.c:473:gst_rtp_base_depayload_handle_buffer:<rtpvp8depay0> 1 <= 100, dropping old packet
> 0:00:25.882654426  2186 0x7fcf7822e4f0 FIXME           videodecoder gstvideodecoder.c:933:gst_video_decoder_drain_out:<vp8dec0> Sub-class should implement drain()

It happen more frequent than gstreamer-receive example

**Comment by Sean-Der** [comment]
Hey @wattanakorn495 

We plan on implementing a Go native JitterBuffer, just haven't had a chance to start on it yet. For now you can try using the GStreamer one. You will need to set the `payload` property dynamically but, this could be a good start. I just used this with Chromium locally.

```
diff --git a/examples/util/gstreamer-sink/gst.go b/examples/util/gstreamer-sink/gst.go
index cb06592..dc712bc 100644
--- a/examples/util/gstreamer-sink/gst.go
+++ b/examples/util/gstreamer-sink/gst.go
@@ -27,9 +27,9 @@ func CreatePipeline(codecName string) *Pipeline {
        pipelineStr := "appsrc format=time is-live=true do-timestamp=true name=src ! application/x-rtp"
        switch codecName {
        case webrtc.VP8:
-               pipelineStr += ", encoding-name=VP8-DRAFT-IETF-01 ! rtpvp8depay ! decodebin ! autovideosink"
+               pipelineStr += ", encoding-name=VP8-DRAFT-IETF-01, clock-rate=90000 ! rtpjitterbuffer name=jitter1 ! rtpvp8depay ! decodebin ! autovideosink"
        case webrtc.Opus:
-               pipelineStr += ", payload=96, encoding-name=OPUS ! rtpopusdepay ! decodebin ! autoaudiosink"
+               pipelineStr += ", payload=111, encoding-name=OPUS, clock-rate=48000 ! rtpjitterbuffer name=jitter2 ! rtpopusdepay ! decodebin ! autoaudiosink"
        case webrtc.VP9:
                pipelineStr += " ! rtpvp9depay ! decodebin ! autovideosink"
        case webrtc.H264:
```

**Comment by wattanakorn495** [comment]
Did you get corrupt video stream? 
i got this
![screenshot from 2018-12-21 15-38-34](https://user-images.githubusercontent.com/41609635/50333165-f64b1780-0536-11e9-87cd-9b64168bf193.jpg)

**Comment by Sean-Der** [comment]
Here is a tuned pipeline @wattanakorn495 

This isn't an exact science, I picked these values from experience so they 100% can be better. But with this pipeline I was able to stream for ~2 mins without any corruption (the pipeline before ~3 seconds max with)

Can you try this patch out and see if it helps?

https://gist.github.com/fc59e15392775ad57241a211629a2c81

To explain the values
```
rtpjitterbuffer latency=1000 # Adds a 1 second delay so we wait for all video packets to arrive
error-resilient=partitions  # Should always have for lossy video
auto-alt-ref # Should always have for lossy video

keyframe-max-dist=10 # Generate keyframes frequently. We really should use PLI but this is easier

cpu-used=5 deadline=1 # Encode in realtime, this lowers the latency but most importantly protects against bursts of data. We want a consistent flow of video data, we don't care as much about bandwidth savings.
```

**Comment by Sean-Der** [comment]
@wattanakorn495 I was also able to completely remove the JitterBuffer from the playing side and still maintain high quality which is pretty cool!

I would also see if you can dump FireFox or Chromiums vp8 encoder settings, those are going to be the gold standard imo.

**Comment by inta495** [comment]
ok. i am going to test your settings.

**Comment by Sean-Der** [comment]
Hey @wattanakorn495 

Were those settings helpful?

**Comment by wattanakorn495** [comment]
your setting give better than before but it still has corruption.
I found settings in chromium source.
[https://chromium.googlesource.com/external/webrtc/stable/src/+/b8671cb0516ec9f6c7fe22a6bbe331d5b091cdbb/modules/video_coding/codecs/vp8/vp8.cc](url)

I was try those setting but it still has few corruption.
and increasing min-quantizer give better result.

**Comment by Sean-Der** [comment]
@wattanakorn495

Unfortunately with live video in some cases corruption is unavoidable for some network conditions, @kc5nra is working on a JitterBuffer which should help a little bit but I don't think there is much more we can do besides tune encoder settings right now.

I would love a PR if you find something that works best though! I am sure it will help a lot of people.

**Comment by Sean-Der** [comment]
Hey @wattanakorn495 

Were these encoding settings helpful? Should we add them to the examples by default? I would love to get this ticket closed out (so doesn't obscure other issues)

thanks!
