### ISSUE TITLE
Add integer wraparound tests to SampleBuilder

### ISSUE THREAD

**Issue by maxhawkins** [pions/webrtc#319]
`SampleBuilder.Pop` doesn't account for uint16 wraparound when `SequenceNumber < maxLate` so packets with low sequence numbers will be dropped.

https://github.com/pions/webrtc/blob/e0313c7cc5167e218ad16513546f20568d076c48/pkg/media/samplebuilder/samplebuilder.go#L77

**Comment by Sean-Der** [comment]
Hey @maxhawkins 

I think I am missing the being dense here :( , but I haven't been able to write a failing test for this yet.

* The `!hasPopped` case seems ok. It just takes the `lastPush` and properly underflows
* the `lastPopSeq + 1` seems ok (it doesn't respect maxLate though) writing a failing test now. but I don't think we have a wrap around issue!
* The for loop walks until we hit our lastPush. It will properly overflow.


```
    var i uint16
    if !s.hasPopped {
        i = s.lastPush - s.maxLate
    } else {
        i = s.lastPopSeq + 1
    }

    for ; i != s.lastPush; i++ {
        curr := s.buffer[i]
        if curr == nil {
            if s.buffer[i-1] != nil {
                break // there is a gap, we can't proceed
            }

            continue // we haven't hit a buffer yet, keep moving
        }

        if !s.hasPopped {
            if s.buffer[i-1] == nil {
                continue // We have never popped a buffer, so we can't assert that the first RTP packet we encounter is valid
            } else if s.buffer[i-1].Timestamp == curr.Timestamp {
                continue // We have the same timestamps, so it is data that spans multiple RTP packets
            }
        }

        // Initial validity checks have passed, walk forward
        return s.buildSample(i)
    }
```

**Comment by maxhawkins** [comment]
I think you're right. Can't find the issue anymore either. Closing this...
