### ISSUE TITLE
Read example jsFiddles from GitHub

### ISSUE THREAD

**Issue by backkem** [pions/webrtc#32]
According to [this documentation](http://doc.jsfiddle.net/use/github_read.html) jsFiddles can be backed by GitHub. This would allow for easier contributions.

**Comment by Sean-Der** [comment]
Really nice find! I will add a `jsfiddle` folder to each example directory, should be a pretty quick win :)

(Unless you want to grab it, don't want to steal your good idea!)

**Comment by backkem** [comment]
By all means, go ahead!
