### ISSUE TITLE
Using webrtcdsp echo cancellation

### ISSUE THREAD

**Issue by Moisesbr** [pions/webrtc#326]
I trying change 'pipelineStr' in file ~/go/src/github.com/pions/webrtc/examples/util/gstreamer-src/gst.go, but without any success, anyone already has any skill, using webrtcdsp plugin

`case webrtc.Opus:`
   `   pipelineStr = pipelineSrc + " ! opusenc ! webrtcdsp ! webrtcechoprobe !" + pipelineStr`

Best Regards
Moisés

**Comment by Sean-Der** [comment]
Hey @Moisesbr 

Thanks for using pion-WebRTC! I would pass these arguments directly to the function, this is how I launch `gstreamer-send` and use my microphone + webrtc elements

`echo $SDP | go run *.go -audio-src 'autoaudiosrc ! webrtcdsp ! webrtcechoprobe ! queue'`

**Comment by Sean-Der** [comment]
Hey @Moisesbr 

If there is anything else we can do feel free to re-open this issue.

We would also love to have you in the pions Slack (you can find the instructions in the README.md) thanks again for using pion-WebRTC!
