### ISSUE TITLE
Can someone help me understand the motivation of this channel?

### ISSUE THREAD

**Issue by Parth** [pions/webrtc#330]
onOpen seems to return a channel, as far as I can tell, no function ever uses this channel. This is an unexported function. 

https://github.com/pions/webrtc/blob/b98909a75b254ac58a6be834bde1a5a68cbfe739/rtcdatachannel.go#L113

My use case: a server (related to a game) will accept many datachannels, I'd like to aggregate them in a single goroutine that'll push updates out to clients. I do this logic in OnOpen for each datachannel, I just want to be sure if OnOpen returns my datachannel won't be closed. Want to make sure I'm modeling the behavior correctly.

**Comment by backkem** [comment]
Hi @Parth, `onOpen` is indeed not exported. It is an internal method that is used to call the `OnOpen` callback safely. It returns a done channel so the caller an optionally wait until the callback is finished. Currently we don't wait for the `OnOpen` callback to finish. We do use this for the `OnDataChannel` callback:
https://github.com/pions/webrtc/blob/b98909a75b254ac58a6be834bde1a5a68cbfe739/rtcpeerconnection.go#L809
Here you can see we call `onDataChannel` and receive on the returned channel to wait until the `OnDataChannel` callback is finished.

**Comment by Parth** [comment]
Thank you for your clarification!

> Currently we don't wait for the OnOpen callback to finish.

So that's not currently used, what's the long term intention of detecting when it returns? 

Essentially I just want to make sure I understand the long term behavior of my goroutine returning OnOpen, currently what my OnOpen does is simply add the *DataChannel to a list of *DataChannels for all the players that are currently connected. I want to be sure that returning OnOpen doesn't imply that I'm ready to close the DataChannel or something like that.

**Comment by backkem** [comment]
It will definitely be fine forever to return `OnOpen`. Currently it is also allowed to block `OnOpen` forever. We'll probably also keep that behavior since it's used in our examples.

**Comment by Parth** [comment]
Awesome, thank you!
