### ISSUE TITLE
Screen capture with gstreamer

### ISSUE THREAD

**Issue by gedw99** [pions/webrtc#341]
Am playing around with using pions to build a remote desktop sharing system with 100% golang.

Anyone know if gstreamer can capture a video of a desktop ?
All the examples only capture video via webcam currently

**Comment by wdouglass** [comment]
ximagesrc is probably what you want, but this is a gstreamer question, not a pions issue.

https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-good/html/gst-plugins-good-plugins-ximagesrc.html

`gst-launch -v ximagesrc ! video/x-raw-rgb,framerate=5/1 ! ffmpegcolorspace ! theoraenc ! oggmux ! filesink location=desktop.ogg`

**Comment by gedw99** [comment]
hey @wdouglass 
thanks for tip.
Is this cross platform ?
