### ISSUE TITLE
Deadlock on RTCPeerConnection.Close()

### ISSUE THREAD

**Issue by mjmac** [pions/webrtc#363]
Still investigating, seems to happen periodically when a pc is closed and another one is created in its place.

> goroutine 55 [semacquire, 4 minutes]:
sync.runtime_SemacquireMutex(0xc0003c1404, 0x900000000)
	/usr/local/Cellar/go/1.11.4/libexec/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc0003c1400)
	/usr/local/Cellar/go/1.11.4/libexec/src/sync/mutex.go:134 +0x153
sync.(*RWMutex).Lock(0xc0003c1400)
	/usr/local/Cellar/go/1.11.4/libexec/src/sync/rwmutex.go:93 +0x49
github.com/pions/webrtc/internal/mux.(*Mux).RemoveEndpoint(0xc0003c1400, 0xc00038a280)
	/Users/mike.macdonald/go/src/github.com/pions/webrtc/internal/mux/mux.go:50 +0x3f
github.com/pions/webrtc/internal/mux.(*Endpoint).Close(0xc00038a280, 0x5da6000, 0x0)
	/Users/mike.macdonald/go/src/github.com/pions/webrtc/internal/mux/endpoint.go:20 +0x5f
github.com/pions/webrtc/internal/srtp.(*session).close(0xc00022a420, 0xc0003fd200, 0x18)
	/Users/mike.macdonald/go/src/github.com/pions/webrtc/internal/srtp/session.go:61 +0x7d
github.com/pions/webrtc/internal/srtp.(*SessionSRTP).Close(0xc00022a420, 0x4b14b60, 0xc000560520)
	/Users/mike.macdonald/go/src/github.com/pions/webrtc/internal/srtp/session_srtp.go:66 +0x3b
github.com/pions/webrtc/internal/network.(*Manager).Close(0xc0003c0600, 0x7, 0x4107923)
	/Users/mike.macdonald/go/src/github.com/pions/webrtc/internal/network/manager.go:108 +0x6c
github.com/pions/webrtc.(*RTCPeerConnection).Close(0xc0004f62c0, 0xc00018fe90, 0xc0000280c0)
	/Users/mike.macdonald/go/src/github.com/pions/webrtc/rtcpeerconnection.go:1321 +0x675
savant-go/app/CameraServer/stream/rtc.(*PeerProxy).StartConnection(0xc00018fec0, 0xc0000280c0, 0x24, 0xc000412c00, 0xbd0, 0x0, 0x0, 0x0, 0x0)
	/Users/mike.macdonald/go/src/savant-go/app/CameraServer/stream/rtc/proxy.go:361 +0xb9e
savant-go/app/CameraServer/server.(*CameraServer).StartRtcConnection(0xc0000d0880, 0x4bd04a0, 0xc00036f500)
	/Users/mike.macdonald/go/src/savant-go/app/CameraServer/server/ipc.go:67 +0x339
reflect.Value.call(0x4ac7600, 0xc0000d0880, 0x1613, 0x4ae94d8, 0x4, 0xc00023fd58, 0x1, 0x1, 0x50, 0x40627f2, ...)
	/usr/local/Cellar/go/1.11.4/libexec/src/reflect/value.go:447 +0x635
reflect.Value.Call(0x4ac7600, 0xc0000d0880, 0x1613, 0xc00023fd58, 0x1, 0x1, 0xc0000d0880, 0x1613, 0x49fc960)
	/usr/local/Cellar/go/1.11.4/libexec/src/reflect/value.go:308 +0xc1
savant-go/app/CameraServer/server.(*CameraServer).invokeForRequest(0xc0000d0880, 0x4bcf060, 0xc000064e00, 0xc0003b812d, 0x12, 0x4bd04a0, 0xc00036f500)
	/Users/mike.macdonald/go/src/savant-go/app/CameraServer/server/ipc.go:215 +0x1d7
savant-go/app/CameraServer/server.(*CameraServer).genControlRequestHandler.func1(0x4bd04a0, 0xc00036f500)
	/Users/mike.macdonald/go/src/savant-go/app/CameraServer/server/ipc.go:234 +0x28a
savant-go/lib/ipc.(*ReqRep).serverReceive(0xc00048b680, 0x4bd5e80, 0xc000082600, 0x0, 0x0)
	/Users/mike.macdonald/go/src/savant-go/lib/ipc/reqrep.go:143 +0x28c
savant-go/lib/ipc.(*ReqRep).serviceLoop(0xc00048b680)
	/Users/mike.macdonald/go/src/savant-go/lib/ipc/reqrep.go:81 +0x4c1
created by savant-go/lib/ipc.(*ReqRep).Start
	/Users/mike.macdonald/go/src/savant-go/lib/ipc/reqrep.go:53 +0x6b

**Comment by mjmac** [comment]
[webrtc-363-full.txt](https://github.com/pions/webrtc/files/2766265/webrtc-363-full.txt)

**Comment by cretz** [comment]
I am finding `Close` hangs as well. If I close the browser first, silent hang. If I don't, I get just a non-stop dump of `Warning: mux: no endpoint for packet starting with 128` to stdout.

**Comment by Sean-Der** [comment]
Ah crud I completely missed this issue, sorry @mjmac and @cretz 

I will try and reproduce and fix now!

**Comment by Sean-Der** [comment]
Hey sorry that I missed this again!

Would you mind trying now? This came from us refactoring the guts, and we just deadlocked when DataChannels never properly started

**Comment by mjmac** [comment]
Thanks! I'll see if I can verify it here... This fell off of my radar because I wasn't able to reliably reproduce it.

**Comment by cretz** [comment]
@Sean-Der - I have confirmed that this fixes the issue both before the browser is closed and after. However, it is a bit annoying that `Endpoint closed` is written to stdout twice (or stderr, didn't check which).

(This library is amazing btw, you have done great work)
