### ISSUE TITLE
PayloadString and PayloadBinary should be a single type

### ISSUE THREAD

**Issue by jech** [pions/webrtc#364]
Is there any good reason why `PayloadString` and `PayloadBinary` are distinct types?  This means that receiver code that doesn't care about the distinction needs to do:

    var data []byte
    switch p := p.(type) {
    case *datachannel.PayloadString:
            data = p.Data
    case *datachannel.PayloadBinary:
            data = p.Data
    }

Wouldn't it be simpler to have

    type Payload struct {
        Type int
        Data []byte
    }

and have client code use the `Type` field for dispatch?

**Comment by backkem** [comment]
I agree that this type switch isn't the most elegant API. It was probably less clear to us when we initially designed the API. We're trying to keep the API stable for now. We'll re-evaluate this when reviewing the API. Some more API suggestions are collected on the [wiki](https://github.com/pions/webrtc/wiki/v2.0.0-Release-Notes).
You may also check out the [detach](https://github.com/pions/webrtc/tree/master/examples/data-channels-detach) example. This shows off an alternative way to interact with data channels.

**Comment by backkem** [comment]
Suggestion added to the Wiki. We'll take it into account in the next API revamp.
