### ISSUE TITLE
Incoming payloads are silently truncated to 8kB

### ISSUE THREAD

**Issue by jech** [pions/webrtc#365]
If incoming payloads are larger than 8kB, they are silently truncated, which causes loss of data.  I believe that there are two issues here:

  * there is no error indication when a packet is truncated;
  * 8kB is too small in any cases (the protocol that I'm trying to implement uses slightly over 16kB).

A simple workaround is to increase the value of `receiveMTU` in `rtcpeerconnection.go`¸ but that's obviously not satisfactory.

**Comment by backkem** [comment]
This is a [known problem](https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Using_data_channels#Concerns_with_large_messages) with the WebRTC API itself. It doesn't provide a good way to handle large messages. All implementations have some limitation. We can increase the default payload size but it would still be an arbitrary limit. A possible solution would be to make this configurable.
Alternatively, You can check out the [detach](https://github.com/pions/webrtc/tree/master/examples/data-channels-detach) example. This shows off an alternative way to interact with data channels. This API allows you to pass your own buffers for reading and writing, allowing you to determine their size. Note that we've probably done limited testing with large buffers so you may uncover some issues.

**Comment by jech** [comment]
> This is a known problem with the WebRTC API itself. It doesn't provide a good way to handle large messages

I still think there should be some sort of indication given to the application that the message has been truncated.

**Comment by jech** [comment]
> This is a known problem with the WebRTC API itself.

I'm confused — your link speaks of a protocol problem with SCTP, not an API problem.  Couldn't the `acceptSRTCP` function reallocate the buffer when it is found to overflow, and then continue reading?  Alternatively, couldn't the `OnMessage` callback return an `io.Reader`, as is done in gorilla.websocket?

**Comment by jech** [comment]
I'm glad to report that Detach solved my problem quite nicely.  Thanks.

**Comment by backkem** [comment]
I agree we should look into adding a warning. We'll keep the issue open untill then.

**Comment by backkem** [comment]
FYI, I did indeed link the wrong info above. For truly sending/receiving any size messages via the WebRTC API, it would have to be extended as suggested in  w3c/webrtc-pc#1732.
