### ISSUE TITLE
Update JS examples to use compression for SDP input/output

### ISSUE THREAD

**Issue by rukavina** [pions/webrtc#373]
I followed the steps from https://github.com/pions/webrtc/blob/master/examples/sfu/README.md and when I paste browser's SD and hit enter the sfu crashes with: illegal base64 data at input byte 4093
Am I doing something wrong?
While I'm very excited that I found this project which looks very promising, I must say it's not very intuitive how to start with it. Some kind of a quick start or an introduction to examples at least would be really helpful

Thanks

**Comment by Sean-Der** [comment]
Hi @rukavina 

It sounds like your over the character limit for stdin (4096) I believe. Maybe try removing the `iceServers` from the jsfiddle. I will see if we can work on compressing this more, but with IPv6 (and other things getting added) this input has just gotten more bloated.

Thanks for the feedback! How do you think we can make the examples better? I am trying to find a good compromise between signal/noise, if the examples are verbose it drives some people off.

thanks!

**Comment by wdouglass** [comment]
at least in go we can use the compress package to compress the SDP before doing base64...I'm not sure the easiest way to deal with that on the javascript side without resorting to some library

**Comment by rukavina** [comment]
I overcame the issue by pasting sd string to a file, and then modified the example to read the content from that file.

**Comment by Sean-Der** [comment]
I am going to opt for not using compression, anyone feel free to push back if you disagree but this is my thinking.

* Adding compression makes it more difficult to people base64 decode themselves and play around with
* SFU example now uses a POST endpoint, which seems to be working for everyone. The code was also really terse (and we plan on allowing it for every example)
