### ISSUE TITLE
Separate the stack into reusable modules

### ISSUE THREAD

**Issue by backkem** [pions/webrtc#38]
I've added the following overview of the WebRTC stack to the [wiki](https://github.com/pions/webrtc/wiki/Relative-Drafts-And-Usages):
<div align="center"><img src="https://github.com/pions/webrtc/wiki/images/stack/WebRTC.png" alt="drawing" width="200" height="200"/></div>

Most of these components deserve their own package (or even repository). This issue can be used to track the progress to that long term goal. Please use the [Golang Slack](https://invite.slack.golangbridge.org/)  #pion channel or [mailing list](https://groups.google.com/forum/#!forum/pion) for long form discussions.

**Comment by Sean-Der** [comment]
I moved this to our [Project Ideas)(https://github.com/pions/webrtc/wiki/Contributing#project-ideas)
