### ISSUE TITLE
Support of more than one data channel

### ISSUE THREAD

**Issue by enobufs** [pions/webrtc#386]
When I was looking at code to understand how SCTP stream ID was determined, I came accross [this code](https://github.com/pions/webrtc/blob/88b495c7f542c74e743fb53038804ef3af7d24e9/rtcpeerconnection.go#L1268-L1270) that I did not fully understand:

```
func (pc *RTCPeerConnection) generateDataChannelID(client bool) (uint16, error) {
	var id uint16
	if !client {
		id++
	}
```

When pc.CreateDataChannel() is called without option or option.id is nil, datachanel ID should be generated automatically according to WebRTC 1.0. However, the above code always assigns 0 because `client` param never becomes false. Consequently, later datachannel overwrites the previous ones.

What I am not sure is, in what situation, the `client` param becomes true? (what was the intention with it?)

**Comment by backkem** [comment]
The I'd is also used as the iterator in the following loop thought:
https://github.com/pions/webrtc/blob/88b495c7f542c74e743fb53038804ef3af7d24e9/rtcpeerconnection.go#L1277
The reason for the code you mentioned is to make the I'd odd/even based on client/server side.

**Comment by backkem** [comment]
@enobufs Is this issue still relevant?

**Comment by enobufs** [comment]
I think I read the code wrong earlier.  I can see using more than one data channel is working file. Closing this issue.
