### ISSUE TITLE
Memory leak in examples/util/gstreamer-src?

### ISSUE THREAD

**Issue by rob-deutsch** [pions/webrtc#393]
https://github.com/pions/webrtc/blob/95fcd7b3a03677c7ccd850c8750990ae07d2afd0/examples/util/gstreamer-src/gst.c#L52-L55

Does there need to be a `g_free(copy)` call after `gst_buffer_extract_dup()`? 

The [gstreamer documentation](https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gstreamer/html/GstBuffer.html#gst-buffer-extract-dup) seems to suggest it is needed. The [golang documentation](https://golang.org/cmd/cgo/) says this is okay when C.GoString() is used; "A few special functions convert between Go and C types by making copies of the data."

**Comment by Sean-Der** [comment]
We free `copy` here https://github.com/pions/webrtc/blob/master/examples/util/gstreamer-src/gst.go#L100

Are you seeing your application leak after running it for a while? I don't know what the best tool for chasing down leaks with `cgo` is though. It does look like ASAN works from this [thread](https://groups.google.com/forum/#!topic/golang-nuts/Cn54bsAk33A) but I have never used it personally!

Would love to hear about your debugging though, and always happy to help in Slack :)

**Comment by rob-deutsch** [comment]
You are totally right! I missed that. Thanks.
