### ISSUE TITLE
how to paste more than 4096 bytes in terminal when running sfu example

### ISSUE THREAD

**Issue by adwpc** [pions/webrtc#400]
The lines are truncated at 4096 byte limit if I paste input to the read

**Comment by backkem** [comment]
Hi @adwpc, this is indeed a frustrating problem. Someone is working on adding a web interface to the example so it becomes easier to paste the input.

**Comment by Sean-Der** [comment]
Hey @adwpc 

Thanks for checking out pion-WebRTC! Sorry about that, would you mind trying again. We updated the SFU example so you can post to an endpoint making it (hopefully) way more usable :)

thanks!
