### ISSUE TITLE
Can not display video on browser when upgrading to pions webrtc 1.2.0 version 

### ISSUE THREAD

**Issue by jiehuang2019** [pions/webrtc#410]
I recently tried to upgrade from 1.1 to 1.2 with pions DTLS. 
After upgrading, I tested using the examples/gstreamer-send. I verified that offer and answer are 
set correctly and the WebRTC state is changed to connected. However, the video data received
by the browser are not decoded and displayed. I looked into the webrtc-internals of chrome and compared
with old version, I noticed several difference:
1) 1.2 is using dtls cipher TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 while the old one is using TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA. see the comparison below:
old one:
Statistics Channel-video-1
--
timestamp | 2/15/2019, 4:27:54 PM
selectedCandidatePairId | Conn-video-1-0
googComponent | 1
dtlsCipher | TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
localCertificateId | googCertificate_30:B4:4B:A9:2A:67:35:6E:E1:33:25:B6:6E:57:54:5A:6B:9A:20:C4:BC:33:74:CF:CC:7C:8A:6B:23:E0:3D:CA
remoteCertificateId | googCertificate_C7:65:3A:A9:40:CB:BE:16:6E:68:F1:E1:57:68:C5:46:00:67:49:3C
srtpCipher | AES_CM_128_HMAC_SHA1_80

1.2 version:

Statistics Channel-video-1
--
timestamp | 2/15/2019, 4:28:07 PM
selectedCandidatePairId | Conn-video-1-0
googComponent | 1
dtlsCipher | TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
localCertificateId | googCertificate_E8:C5:71:8B:DD:B9:46:BD:82:42:E0:FD:46:FE:B9:DA:59:94:83:8F:A5:D6:65:56:60:F1:6D:10:B5:23:8B:83
remoteCertificateId | googCertificate_1D:97:09:DE:17:57:18:E2:08:E0:C3:EC:96:D6:CC:B1:C1:0D:7E:AD:2E:37:CD:39:74:0A:DC:B7:8D:60:80:F4

Another difference is that for the 1.2 version statistics showed that Conn-video-1-0 has data received, but ssrc_4247294462_recv (ssrc) does not have any data received. In old version both of them has data received, the ssrc_4247294462_recv (ssrc) is related to video data displayed in the browser.

I don't know if I missed anything when setting up the WebRTC connection? Pls give any advice that helps.

BR,
Jie

Statistics Conn-video-1-0
--
timestamp | 2/15/2019, 3:47:54 PM
googActiveConnection | true
bytesReceived | 82632864
bytesSent | 701
packetsSent | 2
googReadable | false
requestsSent | 823
consentRequestsSent | 1
responsesSent | 0
requestsReceived | 0
responsesReceived | 526
googChannelId | Channel-video-1
googLocalAddress | 172.24.172.52:59613
localCandidateId | Cand-LzQ4kxAB
googLocalCandidateType | local
googRemoteAddress | 172.24.172.52:38388
remoteCandidateId | Cand-k+HhQ9qM
googRemoteCandidateType | local
googRtt | 0
packetsDiscardedOnSend | 0
googTransportType | udp
googWritable | false

However, 

Statistics ssrc_4247294462_recv
--
 
timestamp | 2/15/2019, 4:29:40 PM
bytesReceived | 0
codecImplementationName | unknown
framesDecoded | 0
mediaType | video
packetsLost | 0
packetsReceived | 0
ssrc | 4247294462
transportId | Channel-video-1
googCaptureStartNtpTimeMs | 0
googCodecName |  
googContentType | realtime
googCurrentDelayMs | 0
googDecodeMs | 0
googFirsSent | 0
googFrameHeightReceived | 0
googFrameRateDecoded | 0
googFrameRateOutput | 0
googFrameRateReceived | 0
googFrameWidthReceived | 0
googInterframeDelayMax | -1
googJitterBufferMs | 0
googMaxDecodeMs | 0
googMinPlayoutDelayMs | 0
googNacksSent | 0
googPlisSent | 0
googRenderDelayMs | 10
googTargetDelayMs | 0
googTrackId | pion2

**Comment by Sean-Der** [comment]
Hey @jiehuang2019 

To use older versions of `pions/webrtc` with `pions/dtls@1.2` you will need [this](https://github.com/pions/webrtc/commit/007660c8cd0ab6c461e188d1c078df6e908655c7) this commit.

Can you try pulling `pions/webrtc@master` with the latest DTLS or you could try applying that commit to your tree? You just need to pass `, SRTPProtectionProfiles: []dtls.SRTPProtectionProfile{dtls.SRTP_AES128_CM_HMAC_SHA1_80}` to your DTLS config

**Comment by Sean-Der** [comment]
Hey @jiehuang2019 

Did you get a chance to try this yet, anything I can do to help?

**Comment by jiehuang2019** [comment]
Hi, 
Thank you very much for your prompt reply. Today is a holiday of us. I will give it a try tomorrow and will let you guy know. It looks to me you suggest the master branch over the 1.2 release version, right? 

Best regards,
Jie

**Comment by Sean-Der** [comment]
Hey @jiehuang2019, no rush at all :) just didn't want to ignore your issue.

`1.2` release of `pions/webrtc` is still supported! Just make sure you are using Go modules.`export GO111MODULE=on` before you run `go get` in the `webrtc` directory.

If you want `pions/dtls@master` you need to use `pions/webrtc@master`. If you use `pions/dtls@master` +  `pions/webrtc@1.2` you will have compatibility issues.

----

`pions/webrtc@master` is changing a lot, but we are getting a lot of great improvements. If you don't mind the churn we should be done with everything in about two weeks! We have documented all our changes here https://github.com/pions/webrtc/wiki/v2.0.0-Release-Notes

thank you for using Pion WebRTC :)

**Comment by jiehuang2019** [comment]
Hi, Sean:

I pulled to the latest master branch of both webrtc and DTLS and it's working now.
Thank you very much for your prompt reply.
Waiting for your latest update in the coming weeks.

Best Regards,
Jie

**Comment by Sean-Der** [comment]
Fantastic, looking forward to feedback and testing!

Thanks again for using pion-WebRTC and sorry for all the changes recently. It should be worth it though!
