### ISSUE TITLE
API: Initialisms are not capitalized consistently

### ISSUE THREAD

**Issue by maxhawkins** [pions/webrtc#417]
In Go, the convention is for [initialisms to be capitalized](https://github.com/golang/go/wiki/CodeReviewComments#initialisms).

This isn't followed consistently in our codebase. For instance, `Ssrc` should be `SSRC`.

**Comment by Sean-Der** [comment]
Fixed with 9cba54cfd06a5ce4128e58e2a97a43e9d395518c

Nice work @maxhawkins
