### ISSUE TITLE
testing: integration testing

### ISSUE THREAD

**Issue by backkem** [pions/webrtc#42]
Automate integration tests between pions and web browsers. Example setup: Use a headless browser in combination with a simple web server to serve a test web page and exchange the SDP offer/answer. Validate the success using a browser API like the [Google Chrome Remote API](https://github.com/wirepair/gcd). Finally make the test part of the [CI](https://docs.travis-ci.com/user/gui-and-headless-browsers/).

**Comment by Sean-Der** [comment]
I moved this to our [Project Ideas](https://github.com/pions/webrtc/wiki/Contributing#project-ideas)
