### ISSUE TITLE
Turn on/off debug by module

### ISSUE THREAD

**Issue by jinleileiking** [pions/webrtc#443]
The log system is bad.

Open a http port to control  the log level or  module?

**Comment by jinleileiking** [comment]
zap is a choice.

**Comment by jinleileiking** [comment]
If grep is enough， this issue can close.

**Comment by Sean-Der** [comment]
Hey @jinleileiking 

I think we do have this ability right now, try something like `PIONS_LOG_TRACE=ice PIONS_LOG_DEBUG=pc,dtls PIONS_LOG_INFO=all`

That will do
- trace: `ice`
- debug:  `pc` `dtls`
- info: everything else!

----

Sorry this isn't documented better, we could do a much better job. This is a big priority for me after `v2.0.0`

**Comment by jinleileiking** [comment]
I read the codes. But I do not notice this. Thanks.

**Comment by jinleileiking** [comment]
Update to wiki
