### ISSUE TITLE
Pions without a browser

### ISSUE THREAD

**Issue by duythien** [pions/webrtc#472]
Hello

I want to use raspberry pi with that library without a browser to live stream and send video, is it support?

**Comment by trivigy** [comment]
@duythien as long as you can run golang with normal network interfaces on the rasberry pi, you should be good to go. I don't see any issues at all. This library does not depend on the browser, it completely re-implements the webrtc for go from scratch. Take a look at this example: https://github.com/pions/webrtc/tree/master/examples/pion-to-pion

**Comment by Sean-Der** [comment]
Hi @duythien 
Thanks for checking out pion!

I have a PR open now that adds an easy example of doing video `Go -> Go` so no browser required! You can check out the PR https://github.com/pions/webrtc/pull/474, but it should also be landing shortly.

If you have any questions feel free to join our Slack and I would love to help you debug there :)

**Comment by duythien** [comment]
@Sean-Der Thanks you. I will try to implement my app

**Comment by Sean-Der** [comment]
Hey @duythien I merged my change (which closed this issue)

If you are still having issues feel free to re-open it! thanks for using Pion again :)
