### ISSUE TITLE
Add WASM support via syscall/js

### ISSUE THREAD

**Issue by albrow** [pions/webrtc#478]
Starting with Go 1.11, there is official first-party support for compiling Go to WebAssembly. As part of a project I'm working on, we were able to build a unified library in Go that supports WebRTC in both browser and standalone environments. It utilizes the `syscall/js` package to call out to the JavaScript WebRTC API when being run in the browser. We also use build tags so that the correct underlying bindings are selected at compile time. There's still some work to do but we've had a lot of success with this approach so far.

We would love to contribute this work back to the community 😄 Would you be interested in a PR that adds support for WebAssembly? Our code is tightly coupled with the `pions/webrtc` package so we would prefer to incorporate it here to make it easier to maintain compatibility.

**Comment by backkem** [comment]
Hi @albrow, thanks for reaching out. This sounds like a really cool addition to the project. Feel free to create a PR so we can discuss the details. The biggest unknowns for us right now seem maintainability and documentation, E.g.: what part of the API works in WASM. On the flip side this could also gain us more insight into compatibility with the WebRTC API spec and an easier way to automate integration testing. Maybe you could shed some light on that. We're definitely interested in exploring this further.

We're always happy to work together and support other projects. We'd love to hear more about what you are building on our work. Feel free to join the #pion channel on the gopher Slack if you want to chat.

**Comment by Sean-Der** [comment]
That is really cool @albrow I have nothing to add over @backkem but really excited to see what this looks like. I haven't touched WASM at all yet, so I don't know enough to have feedback

**Comment by albrow** [comment]
Just in case anyone is following along on GitHub, we've been communicating on Slack and I am planning to create a PR to add this functionality.
