### ISSUE TITLE
dep ensure says sdp/v2 is missing

### ISSUE THREAD

**Issue by orai-arturo** [pions/webrtc#493]
Trying to switch to master so as to get the code that closes DTLS without hanging.

$ go version
go version go1.10.7 darwin/amd64
$ dep version
dep:
 version     : v0.5.0
 build date  : 2018-08-16
 git hash    : 224a564
 go version  : go1.10.3
 go compiler : gc
 platform    : darwin/amd64
 features    : ImportDuringSolve=false

Not importing anything but pions/webrtc and with no vendor directory.
$ dep ensure -add github.com/pions/sdp@master github.com/pions/webrtc@master
Fetching sources...
....
github.com/pions/sdp/v2 from github.com/pions/sdp, but in version master that package is missing.
....

Any suggestions on working around this?  I suppose I could clone but I'd rather not just yet.

**Comment by backkem** [comment]
Hi @orai-arturo,

`/v2` isn't a package that's supposed to exist under `pions/sdp`. This is a convention used by [go modules](https://github.com/golang/go/wiki/Modules) to refer to a major release of a package as documented [here](https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher), [here](https://github.com/golang/go/wiki/Modules#semantic-import-versioning) and some migration strategies [here](https://github.com/golang/go/wiki/Modules#strategies-for-authors-of-pre-existing-v2-packages).
According to the documentation go version 1.10.3+ should support these import paths. However, it seems that go dep doesn't support this yet (and may never) as discussed in this [issue](https://github.com/golang/dep/issues/1962).

I guess we would have to roll back and avoid creating `/v#` dependencies if we want to support go dep.

Thoughts @Sean-Der?

**Comment by Sean-Der** [comment]
Oof that is frustrating.

@orai-arturo if you use this PR does it work https://github.com/golang/dep/pull/1963 ?

We should probably ping them upstream and work on getting that merged. If we roll back I think we will break all our module users :(

Sorry for the frustration @orai-arturo

**Comment by orai-arturo** [comment]
It took me a while to figure out that I wasn't doing anything wrong.  I am new to dep as my last job used glide.

I'll look into getting a patched dep.

**Comment by trivigy** [comment]
@orai-arturo I would highly recommend moving to go modules. It is built into go since 1.11. https://github.com/golang/go/wiki/Modules

**Comment by jinleileiking** [comment]
use go modules. Do not use dep :) 
Close just for now. Reopen as you wish :)

**Comment by orai-arturo** [comment]
Yeah, we're on go 1.10 ;-(
