### ISSUE TITLE
Implement Session Description Protocol (SDP)

### ISSUE THREAD

**Issue by kc5nra** [pions/webrtc#5]
Abstract:
SDP is intended for describing multimedia sessions for the purposes of session announcement, session invitation, and other forms of multimedia session initiation.

https://tools.ietf.org/html/rfc4566

https://github.com/xhs/librtcdc/blob/master/src/sdp.h
https://github.com/xhs/librtcdc/blob/master/src/sdp.c

**Comment by Sean-Der** [comment]
Implemented by https://github.com/pions/webrtc/commit/b2e8189df45618ee037691fc76f5128bdf1215f4
