### ISSUE TITLE
Race in DataChannel.open()

### ISSUE THREAD

**Issue by enobufs** [pions/webrtc#505]
In my app, I am seeing a race condition at the following line:
https://github.com/pions/webrtc/blob/90b85e8c7a5bf92405d2a07fde0069bcfd3ab526/datachannel.go#L189
```go
	dc, err := datachannel.Dial(d.sctpTransport.association, *d.ID, cfg)
	if err != nil {
		d.mu.RUnlock()
		return err
	}

	d.ReadyState = DataChannelStateOpen // <------------ race
	d.mu.RUnlock()

	d.handleOpen(dc)
	return nil
}
```
I believe, we need to use write lock instead of read lock here.

**Comment by Sean-Der** [comment]
nice catch! This sounds right to me, if you cut a PR I can :+1: it right away :)

**Comment by enobufs** [comment]
Will do!

**Comment by enobufs** [comment]
I thought this was fixed, but I am seeing the race at dc.ReadyState again with my app...

I noticed, in my app, that I am reading dc.ReadyState, which is of course not protected by mutex dc has... This would be the same as other parameters `DataChannel` struct defines as [public members](https://godoc.org/github.com/pions/webrtc#DataChannel).

@Sean-Der @backkem I think we need to do something about it asap. What do you guys think the best way would be?  My first reaction is to make all these parameters private and add a method like `GetParameters()`...

**Comment by enobufs** [comment]
I've just remembered that we already have `DataChannelParameters`... We could use it...?

**Comment by enobufs** [comment]
|DataChannel Properties|Mutated by Lib|User Access|Can Race|
|:---|:---:|:---:|:---:|
|Label string|No|Read-only|No|
|Ordered bool|No|Read-only|No|
|MaxPacketLifeTime *uint16|No|Read-only|No|
|MaxRetransmits *uint16|No|Read-only|No|
|Protocol string|No|Read-only|No|
|Negotiated bool|Yes(?)|Read-only|Maybe|
|ID *uint16|No|Read-only|No|
|Priority PriorityType|No|Read-only|No|
|ReadyState DataChannelState|Yes|Read-only|Yes|
|BufferedAmount uint64|Yes|Read-only|Yes|
|BufferedAmountLowThreshold uint64|No|Read/Write|Yes|
