### ISSUE TITLE
Flutter support

### ISSUE THREAD

**Issue by gedw99** [pions/webrtc#512]
## Summary

Support Flutter for webrtc video conferencing. Or at least be open to supporting others doing it.

Desktop
https://github.com/go-flutter-desktop/go-flutter
- Flutter Desktop with golang embedded inside as a "plugin".

Mobile
https://github.com/empirefox/flutter_dial_go
- Flutter Mobile with golang as a plugin inside, and using protobufs for IO between the 2 languages.

## Motivation

Pions has WASM and Browser support moving alone, but i think supporting flutter will allow Desktop and Mobile also.

## Describe alternatives you've considered

https://github.com/cloudwebrtc/flutter-webrtc
But there is much less control because its not written in golang.

## Additional context

In Flutter you can use golang as a "plugin" on the device and so the golang webrtc will work there.
Flutter has a Video Player, Camera & mic access 

https://github.com/flutter/plugins/tree/master/packages/video_player

https://github.com/flutter/plugins/tree/master/packages/camera

https://github.com/hungrymonkey/mic_stream

The hard bit though is the encoding of the video and audio in golang. As far as i know pions relies on gstreamer to do the heavy lifting ?

**Comment by backkem** [comment]
This is a cool idea and we're always open to support projects building on our work. Building the Flutter 'plugin' itself seems out of the scope of this repo thought.

We'll probably want to close this issue to keep the issue list focused on specific problems/features. I'm not sure where to move this idea/info, thought. Maybe we need a better place to feature (potential) projects. Thoughts @Sean-Der ? The Wiki seems an easy option but also less discoverable/interactive.

**Comment by Sean-Der** [comment]
Yea 100% agree with @backkem here

You are correct we don't encode/decode video ourselves, but we don't require GStreamer. You can use ffmpeg or hardware encode/decode and interact with them yourself!

@gedw99 we would love to help though! I am not sure what the next steps forward are? Is there anyone in the flutter community that would be interested in working on this with us? I would love to talk and figure out a way to unblock them.

We currently don't have the bandwidth to add flutter support ourselves, we are trying to release another version of pion WebRTC and that is more the enough work cut out for ourselves :)

Feel free to grab us on https://pion.ly/slack/ always happy to chat on Slack. Also invite any flutter devs and we can figure out a way to build this together!

**Comment by gedw99** [comment]
@Sean-Der Thanks. 
I am working with the webrtc flutter team to get it all working with golang. Its lots of work and so will ask you questions as i move forward.
