### ISSUE TITLE
Why datachannel only canot use getSelectedPair api? pc.getSenders() returns none

### ISSUE THREAD

**Issue by zsmweb** [pions/webrtc#520]
### Your environment.
  - Version: *Release or SHA*
  - Browser: *include version*
  - Other Information - *stacktraces, related issues, suggestions how to fix, links for us to have context*

### What did you expect?
We can use getSelectedPair api  like  peerconnection_media_test .
### What happened?
pc.getSenders() returns none

**Comment by Sean-Der** [comment]
Hey @zsmweb 

`GetSenders` returns `RtpSenders` so it will only return something when you have audio/video tracks that are sending.

This is the same behavior as the [browser](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/getSenders), but please re-open if I am wrong! Thanks for using pion WebRTC :)
