### ISSUE TITLE
Handle disconnected peers with track sharing

### ISSUE THREAD

**Issue by thetooth** [pions/webrtc#523]
### Your environment.
  - Version: ab81640

### What did you do?
Using the basic SFU example with some custom signalling we connect a source(pions) and several consumers(browsers), and let them run. At least 1 in every 10 connections will transition to disconnected after approx 30 seconds which is fine but as soon as one of the peer connections using the sources track terminates all of the remaining peers stop receiving data. The Write method on the local track returns "No Valid Candidate Pairs Available" immediately and all consumers must manually reconnect after the source peer connection has been recreated from scratch (consumers enter an eternal connected state and cannot be closed, source also can't be cleaned up).

### What did you expect?
One transitioning ICE state should not down the whole SFU. Not sure of the best way to fix this, but it would be very useful if we had a "don't give up" parameter for this use case or provide an iterator for the senders that we can extract the offending peer connection from.

Something like
```
for _, s := range localTrack.Senders() {
	if err := s.SendRTP(rtpBuf[:i]); err != nil {
		// User defined
	}
}
or
localTrack.ForEachSender(func(s *webrtc.RTPSender) bool {
	if err := s.SendRTP(rtpBuf[:i]); err != nil {
		return true / false // Where true means break
	}

	return false
})
```

**Comment by Sean-Der** [comment]
@thetooth 

Thinking this over I think we should just discard the 'no peer available error' this mirrors how WebRTC works in the browser also. If you add a `MediaStream` to a `PeerConnection` and it is disconnected you don't get any notification/exception off of it.

If people want to get notification about the ICE status of a peer they can listen to the appropriate ICE callbacks.

Feel free to push back though! I have gotten a good amount of positive feedback about the `Track` API so I think we want to keep that as simple as possible.

**Comment by thetooth** [comment]
Yeah I agree it would add ambiguity to the API. Since the expected behaviour is to disregard the error we should mirror it here.
