### ISSUE TITLE
Firefox Support

### ISSUE THREAD

**Issue by dhannyz** [pions/webrtc#53]
Firefox is using sdparta_N in their SDP offers as a bundle & mid value instead of the hardcoded 'data' value.
Additionally Firefox only supports a max 62bit value as a sessionID, currently the 64bit value in the answer causes Firefox to error during SDP answer parsing.

**Comment by Sean-Der** [comment]
I have started work on this, will open a PR when I make some progress.

**Comment by Sean-Der** [comment]
Hey @dhannyz can you try the PR out, it has full FireFox support (audio, video and datachannels) I hope to merge it soon.

Would love to get you back on pion-WebRTC

thanks!

**Comment by Sean-Der** [comment]
This landed with #73 @dhannyz
