### ISSUE TITLE
Real world examples

### ISSUE THREAD

**Issue by cyantarek** [pions/webrtc#534]
## Summary

as the title says **Please show real world examples like text, audio and video chat/conferencing etc**

**Comment by backkem** [comment]
Hi @cyantarek. We have a collection of examples under the [examples folder](https://github.com/pions/webrtc/tree/master/examples):
- The `data-channels-*` examples show how to send text.
- The `sfu-*` examples show how how to broadcast a video to many peers.

For now, most of these examples are purposefully kept small to make it easier for people to pick up new concepts or learn the API.
We're definitely open to new examples, thought. Are there are any specific examples you would like to see? What do you feel the current examples don't show enough?

**Comment by cyantarek** [comment]
Thanks for pointing to those examples.

Where can I find audio chat/conferencing example? This is what I need also.

**Comment by cyantarek** [comment]
> Are there are any specific examples you would like to see?

Showing examples like peer2peer text/audio/video chat examples will be much more useful, like websockets. Please consider this one.

**Comment by jinleileiking** [comment]
Please check sfu-ws. Close for now. Reopen as you wish.
