### ISSUE TITLE
WriteRTP / SendRTCP API is inconsistent

### ISSUE THREAD

**Issue by maxhawkins** [pions/webrtc#557]
`track.WriteRTP()` is used to send RTP packets. `pc.SendRTCP()` is used to send RTCP packets.

We should use the same prefix for both of these methods so there is consistency.

I was using WriteRTP in my code and when I needed to start sending RTCP packets I expected the method to be called WriteRTCP. I tried finding the method using autocomplete but could not find it because the prefix was different.

**Comment by Sean-Der** [comment]
That makes sense to me!

What do you think of marking `SendRTCP` as deprecated and just have it call `WriteRTCP`?  Or should we just kill it

**Comment by maxhawkins** [comment]
Depreciating is a good idea, but we should kill off the old method before 2.0. That will give people a week or so to transition if they're following HEAD.

**Comment by Sean-Der** [comment]
Yea that sounds good to me! Thanks for pointing this out, whenever you cut this PR it is a instant approve from me :)
