### ISSUE TITLE
Track is not sent back to the sender

### ISSUE THREAD

**Issue by metal3d** [pions/webrtc#560]
### Your environment.
  - Version: 79d29886d9dd508badb0610bf687ff2f78be25bf
  - Browser: Chrome 73.0.3683.86 (Build officiel) (64 bits)
  - OS: Linux, Fedora 29

### What did you do?
I made a simple echo server that receives webcam video and send it back on a local page. Server and client are on the same computer.
It works with a simple aiortc (python) server. I only reimplement the server with gin-gonic and pions/webrtc.

### What did you expect?
I'm expecting the same result: the client sends webcam, and should receive back the track to be read in video element

### What happened?
There is no error, but I never get the track back.

This is the server part:

```go
package main

import (
	"fmt"
	"log"
	"time"

	"github.com/gin-contrib/static"
	"github.com/gin-gonic/gin"
	"github.com/pions/rtcp"
	"github.com/pions/webrtc"
)

func manage(offer webrtc.SessionDescription, answer chan<- *webrtc.SessionDescription) {
	pc, err := webrtc.NewPeerConnection(webrtc.Configuration{})
	if err != nil {
		log.Panic(err)
	}

	pc.OnTrack(func(t *webrtc.Track, receiver *webrtc.RTPReceiver) {
		go func() {
			ticker := time.NewTicker(time.Second * 3)
			for range ticker.C {
				errSend := pc.SendRTCP(&rtcp.PictureLossIndication{MediaSSRC: t.SSRC()})
				if errSend != nil {
					fmt.Println(errSend)
				}
			}
		}()

		log.Println("Track acquired", t.Kind(), t.Codec())
		pc.AddTrack(t)

		log.Println("Track added")
	})

	pc.OnICEConnectionStateChange(func(cs webrtc.ICEConnectionState) {
		log.Println("Ice connection changed to ", cs.String())
		if cs == webrtc.ICEConnectionStateFailed {
			log.Println("Closing peer connection as ICE connection failed")
			pc.Close()
		}
	})

	if err := pc.SetRemoteDescription(offer); err != nil {
		log.Panic("Set remote description failed:: ", err)
	}

	if a, err := pc.CreateAnswer(nil); err != nil {
		log.Panic(err)
	} else {
		pc.SetLocalDescription(a)
		answer <- pc.LocalDescription()
	}

	select {} // I do it for test, commenting this line does nothing
}

// Offer get client offer information and give back an answer.
func Offer(c *gin.Context) {

	offer := webrtc.SessionDescription{}
	c.BindJSON(&offer)

	log.Println("Get offer", offer.Type)

	answer := make(chan *webrtc.SessionDescription)
	go manage(offer, answer)

	c.JSON(200, <-answer)
}

func main() {
	r := gin.Default()
	r.Use(static.Serve("/", static.LocalFile("./statics", false)))
	r.POST("/offer", Offer)
	r.Run(":8080")
}

```

The JS file - take a look on the `console.log("TRACK")` that is working with aiortc but not with pions/webrtc:

```javascript
function E(selector) {
    return document.querySelector(selector);
}

function createPeerConnection() {
    // create a connection and set received track to the video element
    let config = {
        sdpSemantics: 'unified-plan'
    };

    let pc = new RTCPeerConnection(config);
    pc.addEventListener('track', (evt) => {
        // I never get this log with pions/webrtc, it works with aiortc python package:
        console.log("TRACK");
        if (evt.track.kind === "video") {
            E("#track").srcObject = evt.streams[0];
        }
    });
    return pc
}

function start() {
    let pc = createPeerConnection();

    // when captured webcam, add the streams to the peer connection to be sent
    // to the server
    navigator.mediaDevices.getUserMedia({
        audio: false,
        video: true,
    }).then(stream => {
        console.log("Add track");
        stream.getTracks().forEach(track => {
            pc.addTrack(track, stream)
        });
        // we can now try to negociate
        // connection on server
        return negociate(pc);
    }, (err) => {
        console.error(err);
    });
}

function negociate(pc) {
    // create an offer...
    pc.createOffer().then((offer) => {
        // .. then add offer to local description
        return pc.setLocalDescription(offer);
    }).then(() => {

        // we need to wait that ICE Gathering is complete before to send offer to
        // our server.
        return new Promise(resolve => {
            // add event listener on ice gathering state only if it's not complete.
            if (pc.iceGatheringState === 'complete') {
                resolve();
            } else {
                let waitComplete = () => {
                    if (pc.iceGatheringState === 'complete') {
                        pc.removeEventListener('icegatheringstatechange', waitComplete);
                        resolve();
                    }
                }
                pc.addEventListener('icegatheringstatechange', waitComplete);
            }
        });
    }).then(() => {
        // now that Ice Gathering is complete, we can send the offer
        // to our live streaming server.
        let offer = pc.localDescription;

        // "fetch()" is wonderful, really !
        return fetch('/offer', {
            method: 'POST',
            body: JSON.stringify({
                sdp: offer.sdp,
                type: offer.type,
            }),
            headers: {
                'Content-Type': 'application/json',
            }
        });
    }).then(response => {
        return response.json(); // this is a Promise
    }).then(answer => {
        // we received an anwser (resolved fetch response) that is
        // the sdp answer from server. The negociation seems to be OK, so
        // we add it to our RTCPeerConnection object as "remote description".
        return pc.setRemoteDescription(answer);
    }).catch(error => {
        console.error("Error in negociation", error);
    });
}
```

Actualy, I wonder if `pc.AddTrack()` is working as expected, in Python aiortc I do:

```python
async def offer(request):
    params = await request.json()
    offer = RTCSessionDescription(
        sdp=params['sdp'],
        type=params['type']
    )

    pc = RTCPeerConnection()
    pc_id = 'PeerConnection(%s)' % uuid.uuid4()
    pcs.add(pc)
    print('New client', pc_id, request.remote)

    @pc.on('iceconnectionstatechange')
    async def on_ice_change():
        if pc.iceConnectionState == 'failed':
            await pc.close()
            pcs.discard(pc)

    @pc.on('track')
    def on_track(track):
        if track.kind == "video":
            print("Receive track", track.kind)
            pc.addTrack(track)

        @track.on('ended')
        async def ended():
            print("Tracked ended...")

    await pc.setRemoteDescription(offer)

    answer = await pc.createAnswer()
    await pc.setLocalDescription(answer)

    return web.Response(
        content_type='application/json',
        text=json.dumps({
            'sdp': pc.localDescription.sdp,
            'type': pc.localDescription.type,
        })
    )
```
This Python function does the job. It is more or less the same chaining process than those made in Golang.

At this time there is no "error", offer and answer or passed and the only one code part that is not working is `on('track')` that is never called.

So, is there something I does wrong, or is it a bug in pions/webrtc ?

Thanks a lot for your help (and for your great job)

**Comment by metal3d** [comment]
I forget to say that I've got this line that appears in terminal after a while:
```
Failed to retransmit init (nRtos=6): EOF
```

**Comment by Sean-Der** [comment]
Hey @metal3d!

Sorry for the delay, I should have some time to check this out during the weekend :) Just wanted to say thanks for using Pion, and will get this all fixed up

**Comment by Sean-Der** [comment]
Hey @metal3d 

Here is a working echo example https://gist.github.com/Sean-Der/9d0c78041a839809c27a9400a918b154 I think this would be a great example for other people, if you would be interested I would love to see something like this land in our examples!

We would love to have you in [Slack](https://pion.ly/slack) it is a lot easier to help 1:1 there, but will try to explain here also!

- You can't call AddTrack after you have shared the LocalDescription. You have to re-offer if you want to add tracks after things have started.
- We need to re-write the RTP packets to include our new SSRC I do that [here]( https://gist.github.com/Sean-Der/9d0c78041a839809c27a9400a918b154#file-main-go-L48)

Beyond that I didn't make any changes! Thanks again for using Pion WebRTC and hopefully that is helpful :)

**Comment by metal3d** [comment]
Wow, thanks a lot for your help.

Actually, I had the Python example in head and that was not that easy to understand what needed Pion to make it usable.

My goal is to make a multi-client receiver later, with aiortc I had a problem (if one client closes the stream, the server close it for all others... I will take a look later, but as I'm more confortable with Go I give a try to Pion ;) )

Your gist seems to be ok for me, so, really, thanks !

OK, I will join slack channel later.

**Comment by metal3d** [comment]
One more thing, maybe my "example" that you fixed can be nice to be shared to the community. This is a nice "hello world" example to start using Pion

**Comment by Sean-Der** [comment]
Hey @metal3d 

I would love to have this example, maybe we can call it 'echo' or something similar? Would you be interested in contributing it to https://github.com/pion/example-webrtc-applications ? I am happy to do it myself, but I love having contributors because it gets fresh eyes/diverse opinions on everything.

thanks again for using Pion, hopefully your project is going well

**Comment by metal3d** [comment]
@Sean-Der no problem, I only have to find some time - this week is very complicated, a lot of work... 

I actually have several examples here. An echo service, a "visio phone" example and somthing like a "viso chat" but with some problem to resolve.

I will create a branch on a fork as soon as I can, and propose that in a PR.

**Comment by Sean-Der** [comment]
Fantastic, looking forward to it :) Also if there is anything I can do to help with things you are building (even if they aren't open source) always feel free to reach out.

**Comment by Sean-Der** [comment]
Hey @metal3d 

Are you still interested in contributing this? I have been maintaining it here https://gist.github.com/Sean-Der/9d0c78041a839809c27a9400a918b154 (updating it for API changes) I would love to have the PR come from you though!

If you don't mind the commit being attached to me I can land it myself. thanks!

**Comment by metal3d** [comment]
I'm full of works since several weeks, I will take time as soon as I can. Sorry.

**Comment by Sean-Der** [comment]
No worries! I will commit for, and add you as a Co-Author :)

**Comment by VanoGit** [comment]
Hey @Sean-Der 
Could you please tell me why in this example there is no exchange of ica candidates?
I ran this code locally and it tells me that the ice connection failed

**Comment by Sean-Der** [comment]
Hey @VanoGit 

in [reflect](https://github.com/pion/webrtc/blob/master/examples/reflect/main.go#L161) the ICE Candidates are in `peerConnection.LocalDescription()`

We just do this instead of Trickle ICE in the examples to make it easier for developers to get started.

**Comment by VanoGit** [comment]
Hey @Sean-Der 
Thanks for the answer!
Could you please take a look at my code - https://github.com/VanoGit/exAmple?
My goal is to receive video from a web camera and save it on the server.
But so far I cannot establish a connection. I exchange SDP and ice candidates successfully, but after a couple of seconds the ice connection goes into failed status.
I would be very grateful for your help!

**Comment by Antonito** [comment]
Hey @VanoGit, I took a quick look at your code.

Your client is correctly sending an offer and ICE candidates to the server, however it seems your server never sends any ICE candidates.
You either need to implement an `OnICECandidate` handler to forward candidates to your client (take a look at https://github.com/pion/webrtc/blob/d1839c7652bd447b939e7f2f95ffff43410e0eac/examples/pion-to-pion/answer/main.go#L64 ), or include candidates in your SDP answer ( take a look at https://github.com/pion/webrtc/releases/tag/v3.0.0 )

**Comment by VanoGit** [comment]
Hey @Antonito !
Thanks!
At this line https://github.com/VanoGit/exAmple/blob/main/server/signalling.go#L117, I am sending a new candidate to all connections I received before
It is not right?

**Comment by Antonito** [comment]
Oh my bad, you're sending them, right!

However you can't send them right away, you need to have some sort of buffer, on the both side.
With your code, this scenario is possible (and should not):

- `client creates a peerConnection`
- `client starts to gather ICE candidate` (`onicecandidate` is invoked) <--- your client starts signaling candidate to the server, which is not ready (remote state not available yet)
- `client sends offer to server`
- `server replies and starts gathering candidates`

Take a look at https://github.com/pion/webrtc/blob/a54b74cdb736d07a6014da939fd0bac6d5fc4137/examples/pion-to-pion/offer/main.go#L37

What I would do to debug your issue is disabling ICE trickling (cf my previous message) to confirm the issue comes from ICE, and then implement the buffer logic :)

**Comment by VanoGit** [comment]
Hey @Antonito 
Thanks for the answer!
I have simplified the code as much as possible and implemented buffering ice candidates, but the error persists
In the server logs, I see the following:
2021/07/07 21:26:26 Ice connection changed to  checking
2021/07/07 21:26:26 Gathering changed to  gathering
2021/07/07 21:26:56 Ice connection changed to  failed

An event comes that the ice connection failed
Could you tell us for what reasons this may be happening?

I noticed that when I form a response on the server, then in the response IP 0.0.0.0
o = - 6926110003625931442 1625682275 IN IP4 0.0.0.0
Could this have influenced the occurrence of the error?

**Comment by VanoGit** [comment]
Hey @Antonito !
Could you please take a look at my code? I still can't manage with my problem
