### ISSUE TITLE
How to send and receive at the same time?

### ISSUE THREAD

**Issue by brendan-rius** [pions/webrtc#58]
Hi, following your example I was able to receive media from the client to the server, but when I try to add another track to send media from server to client, the handler in `OnTrack` is not called anymore.

If I remove the call to `AddTrack` (that I used to add the track to send data to the client), then it works again

**Comment by backkem** [comment]
Hi @brendan-rius, I think this may be due to limitations in our signaling procedure (possibly #50). We're actively working on building it out further and would love to ensure your use-case is added ASAP. If possible, please share a code snippet to ensure we're looking at the same problem.

**Comment by brendan-rius** [comment]
Here is the code that works (but there is no track added):

```golang
func initiateConnection(b64Offer string) (string) {
	sd, err := base64.StdEncoding.DecodeString(b64Offer)
	if err != nil {
		panic(err)
	}

	// Register only audio codec (Opus)
	webrtc.RegisterCodec(webrtc.NewRTCRtpOpusCodec(webrtc.DefaultPayloadTypeOpus, 48000, 2))

	peerConnection, err := webrtc.New(webrtc.RTCConfiguration{
		ICEServers: []webrtc.RTCICEServer{
			{
				URLs: []string{"stun:stun.l.google.com:19302"},
			},
		},
	})
	if err != nil {
		panic(err)
	}

	peerConnection.Ontrack = func(track *webrtc.RTCTrack) {
		fmt.Println("This is called !!!!") // !!!!!! HERE !!!!!!!
	}

	// Set the remote SessionDescription
	offer := webrtc.RTCSessionDescription{
		Type: webrtc.RTCSdpTypeOffer,
		Sdp:  string(sd),
	}
	if err := peerConnection.SetRemoteDescription(offer); err != nil {
		panic(err)
	}

	// Create an outgoing audio track
	_, err = peerConnection.NewRTCTrack(webrtc.DefaultPayloadTypeOpus, "audio", "label")
	if err != nil {
		panic(err)
	}


	// Sets the LocalDescription, and starts our UDP listeners
	answer, err := peerConnection.CreateAnswer(nil)
	if err != nil {
		panic(err)
	}

	return base64.StdEncoding.EncodeToString([]byte(answer.Sdp))
}
```

and here is the code that does not work (the only difference is that I added a track):

```golang
func initiateConnection(b64Offer string) (string) {
	sd, err := base64.StdEncoding.DecodeString(b64Offer)
	if err != nil {
		panic(err)
	}

	// Register only audio codec (Opus)
	webrtc.RegisterCodec(webrtc.NewRTCRtpOpusCodec(webrtc.DefaultPayloadTypeOpus, 48000, 2))

	peerConnection, err := webrtc.New(webrtc.RTCConfiguration{
		ICEServers: []webrtc.RTCICEServer{
			{
				URLs: []string{"stun:stun.l.google.com:19302"},
			},
		},
	})
	if err != nil {
		panic(err)
	}

	peerConnection.Ontrack = func(track *webrtc.RTCTrack) {
		fmt.Println("This NOT called !!!!") // !!!!!!! HERE !!!!!!!!
	}

	// Set the remote SessionDescription
	offer := webrtc.RTCSessionDescription{
		Type: webrtc.RTCSdpTypeOffer,
		Sdp:  string(sd),
	}
	if err := peerConnection.SetRemoteDescription(offer); err != nil {
		panic(err)
	}

	// Create an outgoing audio track
	opusTrack, err := peerConnection.NewRTCTrack(webrtc.DefaultPayloadTypeOpus, "audio", "label")
	if err != nil {
		panic(err)
	}
	_, err = peerConnection.AddTrack(opusTrack)



	// Sets the LocalDescription, and starts our UDP listeners
	answer, err := peerConnection.CreateAnswer(nil)
	if err != nil {
		panic(err)
	}

	return base64.StdEncoding.EncodeToString([]byte(answer.Sdp))
}
```

**Comment by brendan-rius** [comment]
If you give me some guidance on where I should start to look at, I can maybe give you a hand as this is something I really need :)

**Comment by backkem** [comment]
That would be awesome. As a quick hack I would try to force the direction to RTCRtpTransceiverDirectionSendrecv on signaling.go:306 like on line 334.
Please also consider joining the #pions channel of the gophers slack. We're pretty active in there and will be able to communicate a bit easier.

**Comment by brendan-rius** [comment]
Should be fixed in #60  (at least temporarily)

**Comment by Sean-Der** [comment]
Hi @brendan-rius @backkem 

What are the next steps here? Do we just need to query direction at build time (should be a simple fix!)

**Comment by brendan-rius** [comment]
@Sean-Der yes

**Comment by Sean-Der** [comment]
@brendan-rius With the latest changes I pushed this is now possible, I hacked up the SFU [example](https://gist.github.com/60bda7c9e6f63c9f359c42f843ae0141) to show it in action.

If there is anything else I can do would love to hear! Thanks
