### ISSUE TITLE
Implement WebRTC Data Channels (RTCDC)

### ISSUE THREAD

**Issue by kc5nra** [pions/webrtc#6]
Abstract:
Direct interactive rich communication using audio, video, and data between two peers' web-browsers.  This document specifies the non-media data transport aspects of the WebRTC framework.  It provides an architectural overview of how the Stream Control Transmission Protocol (SCTP) is used in the WebRTC context as a generic transport service allowing WEB-browsers to exchange generic data from peer to peer.

https://tools.ietf.org/html/draft-ietf-rtcweb-data-channel-13

https://github.com/xhs/librtcdc/blob/master/src/rtcdc.h
https://github.com/xhs/librtcdc/blob/master/src/rtcdc.c

**Comment by belohlavek** [comment]
What happened to this?
