### ISSUE TITLE
Can we have an example for attach current stream to other webRTC 

### ISSUE THREAD

**Issue by tabvn** [pions/webrtc#63]
Hi Pions

could you create an example show how to attach a stream track (track *webrtc.RTCTrack) from webRTC call A to another WebRTC call B and send it to B browser ? 

* Plus could we have sample to push stream track to another RTMP server :) 

Best regards,
Toan

**Comment by backkem** [comment]
Hi tabvn, @brendan-rius has kindly offered to create this kind of example.

**Comment by tabvn** [comment]
Cool, i 'm look forward to hearing from that soon. If possible we do have an example about push webRTC stream track into another stream server like RTMP (we may use ffmpeg)

**Comment by tabvn** [comment]
> Hi @tabvn, @brendan-rius has kindly offered to create this kind of example. Feel free to join the #pions channel of the gopher slack. We're really active on there.


could you invite me on slack to group chat ? toan@tabvn.com

Best regards
Toan

**Comment by Sean-Der** [comment]
Hey @tabvn you can create an account here https://invite.slack.golangbridge.org/

Once you have joined you can just do `/join #pion` and you are all set! Look forward to seeing you there :)

**Comment by Sean-Der** [comment]
I am working on this in the `proxy` branch, should be landing really soon!

**Comment by tabvn** [comment]
cool, So we are look forward to seeing it soon 👍

**Comment by Sean-Der** [comment]
Hey @tabvn @brendan-rius this is done!

Mind checking out the PR https://github.com/pions/webrtc/pull/162

**Comment by Sean-Der** [comment]
I haven't handled the RTMP case yet, but this example allows you to send video once (and then send it out to as many peers as you want)
