### ISSUE TITLE
Sending to the browser a RTP Stream source

### ISSUE THREAD

**Issue by rosimildo** [pions/webrtc#69]
Hi there, and thanks for the excellent work!
So far, this project looks very promissing!

I am wondering if there is anything on works to get a generic RTP source to the browser. It would be similar to the gstreamer example, but reading the media from an RTP source which could be the output of gstreamer itself, ffmpeg or vlc.

If there is none, in about a month I should be able to contribute a bit, if some tips out given on how to get that working!

**Comment by backkem** [comment]
Welcome @rosimildo.
A quick overview of what we have right now. If you look at the `gstreamer-send` example you'll see the following line:
```Go
webrtc.RegisterDefaultCodecs()
```
This line initializes some default 'codecs' which are shipped with the library.
Note that when referring to a 'codec' we mean a collection of:
- Some meta data that defines the codec. This is used in WebRTC to find matching capabilities between the peers.
- A Payloader used to split the stream of media data into packets for sending over the network.
The actual conversion of video is (at least currently) out of scope of our efforts.
In addition, you can define your own codec. One way to do this is used in the save-to-disk example:
```Go
webrtc.RegisterCodec(webrtc.NewRTCRtpOpusCodec(webrtc.DefaultPayloadTypeOpus, 48000, 2))
```
You can even go further and define a completely new codec. You can use the contents of `NewRTCRtpOpusCodec` as an example.
We also support multiple peer connections with different codecs. This can be done by creating your own `MediaEngine` and registering it with the peer connection using `SetMediaEngine`.

A fully generic way to ingest media would have to identify the codec and supply the required details to the library as described above. I currently don't know of any such efforts.

Hopefully this provides some insight. Let me know if you have any additional questions.

**Comment by rosimildo** [comment]
Thanks Backkem for your quick answer!

For now, I am browsing the project to get familiar with, and hopefully soon to be able to play with the examples..... thanks!

**Comment by backkem** [comment]
Great, If you have any questions while browsing you can always find us in the #pion channel of the Gopher slack.

**Comment by Sean-Der** [comment]
Hey @rosimildo, thanks for checking out pion-WebRTC! 

We have examples of GStreamer generating RTP traffic (and consuming it) I am happy to add more examples though (I think this covers what your looking for though)

Feel free to reopen this if you have a specific example that would help developers learning this library! And always happy to chat in Slack.
