### ISSUE TITLE
undefined: stun.UseCandidate, stun.IceControlling and stun.Priority

### ISSUE THREAD

**Issue by programmingman** [pions/webrtc#80]
```
# github.com/pions/webrtc/pkg/ice
../../pkg/ice/agent.go:92:4: undefined: stun.UseCandidate
../../pkg/ice/agent.go:93:4: undefined: stun.IceControlling
../../pkg/ice/agent.go:94:4: undefined: stun.Priority
```

**Comment by Sean-Der** [comment]
Hey @programmingman your copy of `github.com/pions/pkg` is out of date.

If you `go get -u` in `github.com/pions/webrtc` or `git pull` in `github.com/pions/pkg` this will be fixed.

mind closing the issue if that fixes it for you? thanks!

**Comment by programmingman** [comment]
@Sean-Der it's my negligence,thanks.

**Comment by Sean-Der** [comment]
It needs a better design, I will see if I can find a way to make it a better experience! Thank you for using `pion-WebRTC`

**Comment by programmingman** [comment]
@Sean-Der My pleasure.
