### ISSUE TITLE
no binding success response

### ISSUE THREAD

**Issue by wattanakorn495** [pions/webrtc#87]
I test pions data-channel examples on this scenerio
intenet <-> wifi router nat <-> PC1 (windows 10 + enable wifi hospot) <-- wifi hospot --> PC2 (ubuntu)
i run pions on PC2 and js on PC1
it is no binding success responce send form PC2 to PC1
but javascript peers on chrome works fine

js to js
192.168.137.1	     192.168.137.251	STUN	138	Binding Request user: Uplx:0NIC
192.168.137.251	192.168.137.1	STUN	106	Binding Success Response XOR-MAPPED-ADDRESS: 192.168.137.1:50957

pions to js
192.168.137.1	192.168.137.251	STUN	154	Binding Request user: UOQxxHfDaGILywYj:/Tlg
192.168.137.1	192.168.137.251	STUN	154	Binding Request user: UOQxxHfDaGILywYj:/Tlg
192.168.137.1	192.168.137.251	STUN	154	Binding Request user: UOQxxHfDaGILywYj:/Tlg
192.168.137.1	192.168.137.251	STUN	154	Binding Request user: UOQxxHfDaGILywYj:/Tlg
...
and pions print
Could not find remote candidate for 192.168.137.1:53284

**Comment by Sean-Der** [comment]
Hey @wattanakorn495 sorry for the delay!

I am going to look at this soon, been a bit swamped recently.

**Comment by inta495** [comment]
I changed these line in agent.go and it works.
both controlling and controlled agent call pingCandidate
 in pingCandidate
`

if a.isControlling {

		msg, err := stun.Build(stun.ClassRequest, stun.MethodBinding, stun.GenerateTransactionId(),
			&stun.Username{Username: a.remoteUfrag + ":" + a.LocalUfrag},
			&stun.UseCandidate{},
			&stun.IceControlling{TieBreaker: a.tieBreaker},
			&stun.Priority{Priority: uint32(local.GetBase().Priority(HostCandidatePreference, 1))},
			&stun.MessageIntegrity{
				Key: []byte(a.remotePwd),
				},
			&stun.Fingerprint{},
			)

		if err != nil {
			fmt.Println(err)
			return
		}

		a.outboundCallback(msg.Pack(), &stun.TransportAddr{
			IP:   net.ParseIP(local.GetBase().Address),
			Port: local.GetBase().Port,
			}, &net.UDPAddr{
			IP:   net.ParseIP(remote.GetBase().Address),
		Port: remote.GetBase().Port,
		})
	} else {
		msg, err := stun.Build(stun.ClassRequest, stun.MethodBinding, stun.GenerateTransactionId(),
			&stun.Username{Username: a.remoteUfrag + ":" + a.LocalUfrag},
			&stun.UseCandidate{},
			&stun.IceControlled{TieBreaker: a.tieBreaker},
			&stun.Priority{Priority: uint32(local.GetBase().Priority(HostCandidatePreference, 1))},
			&stun.MessageIntegrity{
				Key: []byte(a.remotePwd),
				},
			&stun.Fingerprint{},
			)

		if err != nil {
			fmt.Println(err)
			return
		}

		a.outboundCallback(msg.Pack(), &stun.TransportAddr{
			IP:   net.ParseIP(local.GetBase().Address),
			Port: local.GetBase().Port,
			}, &net.UDPAddr{
			IP:   net.ParseIP(remote.GetBase().Address),
		Port: remote.GetBase().Port,
		})
	}
`

and in agentTaskLoop
`


				if assertSelectedPairValid() {

					a.Unlock()
					continue
				}

				for _, localCandidate := range a.LocalCandidates {
					for _, remoteCandidate := range a.remoteCandidates {
						a.pingCandidate(localCandidate, remoteCandidate)
					}
				}
			} else {
				if assertSelectedPairValid() {
					a.Unlock()
					continue
				}

				for _, localCandidate := range a.LocalCandidates {
					for _, remoteCandidate := range a.remoteCandidates {
						a.pingCandidate(localCandidate, remoteCandidate)
					}
				}
			}
`

**Comment by wattanakorn495** [comment]
I add these line in agent.go and it works
both controlling and controlled agent call pingCandidate
in pingCandidate
`
if a.isControlling {

		msg, err := stun.1Build(stun.ClassRequest, stun.MethodBinding, stun.GenerateTransactionId(),
			&stun.Username{Username: a.remoteUfrag + ":" + a.LocalUfrag},
			&stun.UseCandidate{},
			&stun.IceControlling{TieBreaker: a.tieBreaker},
			&stun.Priority{Priority: uint32(local.GetBase().Priority(HostCandidatePreference, 1))},
			&stun.MessageIntegrity{
				Key: []byte(a.remotePwd),
			},
			&stun.Fingerprint{},
		)
		if err != nil {
			fmt.Println(err)
			return
		}

		a.outboundCallback(msg.Pack(), &stun.TransportAddr{
			IP:   net.ParseIP(local.GetBase().Address),
			Port: local.GetBase().Port,
		}, &net.UDPAddr{
			IP:   net.ParseIP(remote.GetBase().Address),
			Port: remote.GetBase().Port,
		})
	} else {
		msg, err := stun.Build(stun.ClassRequest, stun.MethodBinding, stun.GenerateTransactionId(),
			&stun.Username{Username: a.remoteUfrag + ":" + a.LocalUfrag},
			&stun.UseCandidate{},
			&stun.IceControlled{TieBreaker: a.tieBreaker},
			&stun.Priority{Priority: uint32(local.GetBase().Priority(HostCandidatePreference, 1))},
			&stun.MessageIntegrity{
				Key: []byte(a.remotePwd),
			},
			&stun.Fingerprint{},
		)
		if err != nil {
			fmt.Println(err)
			return
		}

		a.outboundCallback(msg.Pack(), &stun.TransportAddr{
			IP:   net.ParseIP(local.GetBase().Address),
			Port: local.GetBase().Port,
		}, &net.UDPAddr{
			IP:   net.ParseIP(remote.GetBase().Address),
			Port: remote.GetBase().Port,
		})
	}`
in agentTaskLoop
`
	if a.isControlling {

				if assertSelectedPairValid() {
					a.Unlock()
					continue
			                }
				for _, localCandidate := range a.LocalCandidates {
					for _, remoteCandidate := range a.remoteCandidates {
						a.pingCandidate(localCandidate, remoteCandidate)
					}
				}
			} else {
				if assertSelectedPairValid() {
					a.Unlock()
					continue
				}

				for _, localCandidate := range a.LocalCandidates {
					for _, remoteCandidate := range a.remoteCandidates {
						a.pingCandidate(localCandidate, remoteCandidate)
					}
				}
			}`

**Comment by backkem** [comment]
Thanks for looking into this. Are you comfortable with (or interested in learning) sending a pull request for the proposed changes? This would really help us to make sure we're looking at the correct changes, run all the required checks and correctly attribute these findings to you. We'll be sure to help you through this process. Please conciser joining the #pion channel of gophers slack if you would like some more hands-on support.

**Comment by Sean-Der** [comment]
Hey @wattanakorn495 does this work for you in master now that your PR has landed? Mind closing it out if it does.

thanks!
