### ISSUE TITLE
sdp rtsp -> to sdp rtp

### ISSUE THREAD

**Issue by deepch** [pions/webrtc#89]
hello

I'm start create sample use pions/webrtc without gstreamer for rtsp to webrtc streaming

https://github.com/deepch/RTSPtoWebRTC

so far this is a very early code but it already works.
But at the start he starts producing very slowly.

I can not understand how you better give away packages

sps , pps , key , p, p, p 
or use h.264 annex b
00 00 01 sps 00 00 01 pps 00 00 01 key

I think I might be able to supplement the sdp information with sps and pps so that the playback starts faster. Prompt how to do this?

**Comment by trivigy** [comment]
@deepch Not really sure how to help you with this. Could you give more feedback.

**Comment by Sean-Der** [comment]
Hey @deepch sorry for the slow response.

Who is producing the video? pion-WebRTC needs to implement RTCP so we can emit FIR/PLI. Currently pion-WebRTC doesn't request a full keyframe when it connects (so if there is any packet loss/peer doesn't connect right away) you will see this long gap. I am currently implementing this in the `proxy` branch.

If video is slow to play in the browser, then I would tune how you are producing the video (much smaller keyframe interval etc..) if you can't dynamically control the encoder.

Also if you join the #pion Slack channel on the [gophers](https://invite.slack.golangbridge.org/) instance you can get much quicker responses. Thanks!

**Comment by Sean-Der** [comment]
Hey @deepch pion-WebRTC can now emit PLIs

Can you emit a PLI against the media tracks that have slow playback, like [here](https://github.com/pions/webrtc/blob/master/examples/sfu/main.go#L74) this will cause video playback to start much quicker.

If you want to confirm the behavior try using the SFU example and comment out the PLI emit (it will take ~90 seconds)
