### ISSUE TITLE
Passing variadic arguments in place of options or configs

### ISSUE THREAD

**Issue by trivigy** [pions/webrtc#96]
Hey guys, I wanted to explain a situation here and wanted to get some input with a proposed deviation from the general API/JS spec. This way we are going to make the library more golang like while actually solving a tiny but really annoying problem. I would greatly appreciate your input on the proposal.

**Problem**
Since the WebRTC spec was written for JS with has first class object, which are basically just maps like structures. A lot of the functions were defined with an "options" like optional parameter. In js this is totally fine because we can declare defaults for function arguments and so if only a part of the object is being set we can just access the default. Unfortunately in golang defaults are not a possibility. In addition this leads to an ugly interface where we sort of HAVE to pass something in place of the options argument. Here are a few examples:
```golang
_, err = pc.CreateDataChannel("data", RTCDataChannelInit{})
	assert.Nil(t, err)
```
```golang
_, err := New(RTCConfiguration{})
	assert.Nil(t, err)
```
We could semi solve this problem by setting those arguments to a pointer passing but this still will require our users to pass a nil in the argument. Which is still pretty ugly and stupid.
```golang
_, err = pc.CreateDataChannel("data", nil)
	assert.Nil(t, err)
```
```golang
_, err := New(nil)
	assert.Nil(t, err)
```
More so, these solutions do not address the default values within the actual options objects that need to be passed. For example this is really problematic with `RTCDataChannelInit.Ordered` which needs to default to the opposite of the zero value (`true`). This means if I am calling:
```golang
_, err = pc.CreateDataChannel("data", RTCDataChannelInit{})
	assert.Nil(t, err)
```
How can one know if `RTCDataChannelInit.Ordered` was set to its golang zero value (`false`) or actually just not set at all? The proposed solutions from above make the code start looking super ugly as we try to add random checks and conversions. Blah... Golang is great at some stuff and is annoying as hell for others.

**Solution**
Although this solution is not 100% according with the spec,  it does at least will resemble the use of the specs but will be purely a golang solution.
The idea we could be declare those objects as varidic options functions and pass arguments with `WithXYZ()` functions. Thus for example the `CreateDataChannel` definition could look something like:
```golang
func (pc *RTCPeerConnection) CreateDataChannel(label string, options ... func(opt ... func() error) error) (*RTCDataChannel, error) {...}
```
So that when the users are using the functions all of the below use cases would be valid:
```golang
_, err = pc.CreateDataChannel("data")

_, err = pc.CreateDataChannel("data", WithRTCDataChannelInit())

_, err = pc.CreateDataChannel("data", WithRTCDataChannelInit(
	WithOrdered(),
	WithMaxPacketLifeTime(),
))
```

The one problem I see with this is there is not compile time checking which sucks but I guess we cannot win EVERY battle.

**Comment by trivigy** [comment]
One proposal came from @backkem is to get rid of wrapper options function like `WithRTCDataChannelInit` and just pass the arguments in the outer function so that the use case will look more like:
```golang
_, err = pc.CreateDataChannel("data",
	WithOrdered(),
	WithMaxPacketLifeTime(),
)
```

**Comment by Sean-Der** [comment]
Another solution (and my favorite) is the one you did with the SDP code, use pointers to show default values.

That is a pain because you can't do `&true` but you could do something like `&webrtc.NullBool{true}` which means things can be a one liner.

I think we need to do something that involves passing a struct, otherwise the API is going to look foreign if you compare a JS WebRTC tutorial to pion-WebRTC (and it would be nice if we don't have to rewrite everything because of divergence)

**Comment by trivigy** [comment]
@Sean-Der Hahaha... It is almost like we go back and forth between wanting to be like JS API and not. I started implementing the other approach already but I am happy to change it. Keep in mind that the divergence we are talking about is only going to be related to the argument intake of the different functions that have options/configs allowed. Generally speaking I want to stay as close to the JS API as possible but in this case golang really sucks and therefore I am arguing that it is okay. At the end of the day worst case the only public part that changes are the arguments and as long as I will document it really well, it will be fine. On the positive side, specifically for you @Sean-Der , the API will finally get a unique golang style that is unique to golang and not to the JS API. And as long as we stick to it, this will be a signature mark.

Anyway, all in all I am not opposed to it because it seems like the least of all evils but I am sure I am not thinking through some challenges that WILL come up from this design. So... I am going to leave this decision to you. Ultimately it needs to be aligned with your goals because at some point when the library is mature enough I am going to transition out to my own stuff and you will be the one running around promoting it and teaching people how to use it. Fair?! :stuck_out_tongue_winking_eye:

Q. This means we are going to have these `webrtc.NilBool{}` types for every primitive. **a**. are you happy with that? **b**. If so, can we agree to have it as a separate package so we could use them in all the other pkgs as well. Like the sdp.

**Comment by trivigy** [comment]
I have been messing around with this for quiet a while and no matter how I do it, if we make it using nil the way I did in sdp it will require the user to either use wrapper functions which is ugly or write extra code code the way I did with sdp which is hard because not all users will know that trick. Either way I am kinda leaning more and more towards my proposal as I mess around with this.

**Comment by trivigy** [comment]
https://stackoverflow.com/questions/30716354/how-do-i-do-a-literal-int64-in-go

Found this and wanted to put it here for reference. Gosh I find like golang is missing some seriously basic functionality.

**Comment by trivigy** [comment]
@Sean-Der @kc5nra after a short convo with some of the people in the golang community I am going to do what @Sean-Der wanted. I am going to implement our own special structs that default nil based primitives.

**Comment by trivigy** [comment]
For record keeping, this is what I am going to re-implement and imitate. Credits go to whoever implemented this library. https://golang.org/pkg/database/sql/#NullInt64
